### ISSUE TITLE
6.2.0 with bug

### ISSUE THREAD

**Issue by evilebottnawi** [stylelint/stylelint#1131]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

@davidtheclark @jeddy3 

`npm i stylelint`

```shell
module.js:341
    throw err;
    ^

Error: Cannot find module 'tape'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/path/to/node_modules/stylelint/dist/testUtils/testRule.js:11:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/path/to/node_modules/stylelint/dist/testUtils/index.js:25:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/path/to/node_modules/stylelint/dist/index.js:21:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

**Comment by davidtheclark** [comment]
Puke.

**Comment by davidtheclark** [comment]
Try 6.2.1

**Comment by evilebottnawi** [comment]
@davidtheclark all ok, thanks

**Comment by davidtheclark** [comment]
Thanks for pointing that out!
