### ISSUE TITLE
Invalid CSS triggers crash with "Error: Table data must not contain control characters"

### ISSUE THREAD

**Issue by ohskylab** [stylelint/stylelint#1241]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug which produces an "Error: Table data must not contain control characters" (from [gajus/table](https://github.com/gajus/table/blob/7464b27999c5c6da43c754fb5f94931423d41839/src/validateTableData.js#L45)) and a stack trace when linting invalid CSS.

> Which rule, if any, is this issue related to?

Appears to be `no-browser-hacks`.

> What CSS is needed to reproduce this issue?

__Note the comma after second selector__. Both selectors required to reproduce error.

```css
.Test,
.Test1, {
  width: auto;
}
```

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "rules": {
    "no-browser-hacks": true
  }
}
```

> Which version of stylelint are you using?

`6.3.3` (tested in `5.4.0` as well, which seems fine: looks like a regression somewhere?)

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint 'test.css'`, run as npm script with config stored in `package.json`:

```json
{
  "name": "stylelint-no-browser-hacks-bug",
  "version": "0.0.0",
  "private": "true",
  "scripts": {
    "test": "stylelint --version && stylelint 'test.css'"
  },
  "devDependencies": {
    "stylelint": "6.3.3"
  },
  "stylelint": {
    "rules": {
      "no-browser-hacks": true
    }
  }
}
```

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No.

> What did you expect to happen?

Error message using stylelint reporter as per `5.x`, rather than a crash :)

> What actually happened (e.g. what warnings or errors you are getting)?

With `6.3.3`:

```shell
$ npm test

> stylelint-no-browser-hacks-bug@0.0.0 test /Users/paul/Projects/_contrib/stylelint-bug
> stylelint --version && stylelint 'test.css'

6.3.3
Error: Table data must not contain control characters.
    at /Users/paul/Projects/_contrib/stylelint-bug/node_modules/table/dist/validateTableData.js:60:23
    at arrayEach (/Users/paul/Projects/_contrib/stylelint-bug/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/paul/Projects/_contrib/stylelint-bug/node_modules/lodash/forEach.js:38:10)
    at /Users/paul/Projects/_contrib/stylelint-bug/node_modules/table/dist/validateTableData.js:58:31
    at arrayEach (/Users/paul/Projects/_contrib/stylelint-bug/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/paul/Projects/_contrib/stylelint-bug/node_modules/lodash/forEach.js:38:10)
    at exports.default (/Users/paul/Projects/_contrib/stylelint-bug/node_modules/table/dist/validateTableData.js:47:27)
    at exports.default (/Users/paul/Projects/_contrib/stylelint-bug/node_modules/table/dist/table.js:120:35)
    at formatter (/Users/paul/Projects/_contrib/stylelint-bug/node_modules/stylelint/dist/formatters/stringFormatter.js:157:33)
    at /Users/paul/Projects/_contrib/stylelint-bug/node_modules/stylelint/dist/formatters/stringFormatter.js:12:15
npm ERR! Test failed.  See above for more details.
```

And with `5.4.0`:

```shell
$ npm test

> stylelint-no-browser-hacks-bug@0.0.0 test /Users/paul/Projects/_contrib/stylelint-bug
> stylelint --version && stylelint 'test.css'

5.4.0

test.css
1:1 Unexpected selector hack ".Test,
.Test1," (no-browser-hacks)
npm ERR! Test failed.  See above for more details.
```

Appreciate that this is a bit of an edge-case, submitting because I came across it in a legacy codebase and it took me a good while to track down the source of the problem.

**Comment by evilebottnawi** [comment]
@ohskylab see interesting, looks as bug in https://github.com/ben-eb/stylehacks

**Comment by evilebottnawi** [comment]
@ohskylab not reproduce on node v6

**Comment by ohskylab** [comment]
@evilebottnawi Hmm, interesting, I see it on node `v6.1.0`. I tested on `v4.4.0` too, with the same results.

I've published my test case here: [ohskylab/stylelint-bug](https://github.com/ohskylab/stylelint-bug). I've run that on Codeship, to help rule out the chance of it being something up with my machine (if not my config skills!) 

Builds fine if I remove the dodgy comma, but fails in the same way as on my local if I don't:

```shell
> stylelint-no-browser-hacks-bug@0.0.0 test /home/rof/src/github.com/ohskylab/stylelint-bug
> node -v && stylelint --version && stylelint 'test.css'

v6.1.0
6.3.3
Error: Table data must not contain control characters.
at /home/rof/src/github.com/ohskylab/stylelint-bug/node_modules/table/dist/validateTableData.js:60:23
at arrayEach (/home/rof/src/github.com/ohskylab/stylelint-bug/node_modules/lodash/_arrayEach.js:15:9)
at forEach (/home/rof/src/github.com/ohskylab/stylelint-bug/node_modules/lodash/forEach.js:38:10)
at /home/rof/src/github.com/ohskylab/stylelint-bug/node_modules/table/dist/validateTableData.js:58:31
at arrayEach (/home/rof/src/github.com/ohskylab/stylelint-bug/node_modules/lodash/_arrayEach.js:15:9)
at forEach (/home/rof/src/github.com/ohskylab/stylelint-bug/node_modules/lodash/forEach.js:38:10)
at exports.default (/home/rof/src/github.com/ohskylab/stylelint-bug/node_modules/table/dist/validateTableData.js:47:27)
at exports.default (/home/rof/src/github.com/ohskylab/stylelint-bug/node_modules/table/dist/table.js:120:35)
at formatter (/home/rof/src/github.com/ohskylab/stylelint-bug/node_modules/stylelint/dist/formatters/stringFormatter.js:157:33)
at /home/rof/src/github.com/ohskylab/stylelint-bug/node_modules/stylelint/dist/formatters/stringFormatter.js:12:15
npm ERR! Test failed.  See above for more details.
```

**Comment by evilebottnawi** [comment]
@ohskylab thanks for detail response, i get around to it in the near future

**Comment by evilebottnawi** [comment]
@ohskylab just now we merge https://github.com/stylelint/stylelint/pull/1244, can you test again?

**Comment by evilebottnawi** [comment]
@ohskylab install throw `git clone` and test

**Comment by evilebottnawi** [comment]
reproduced on latest node.

**Comment by ohskylab** [comment]
@evilebottnawi Same results with `master`, I'm afraid. Output below (but please tell me if there's anything wrong with my test, I've not had to build and run stylelint from source before).

```shell
$ git last
commit a44e66be45faa5cee5c92dcba061a836ca2f1cb7
Merge: aa04d50 aba4dce
Author: Evilebot Tnawi <sheo13666q@gmail.com>
Date:   Wed May 11 18:23:54 2016 +0300

    Merge pull request #1245 from stylelint/issue-1240

    Rule `no-unknown-animations` now ignores `ease` value.
$ cat .stylelintrc
{
  "rules": {
    "no-browser-hacks": true
  }
}
$ node cli.js test.css
Error: Table data must not contain control characters.
    at /Users/paul/Projects/_contrib/stylelint/node_modules/table/dist/validateTableData.js:60:23
    at arrayEach (/Users/paul/Projects/_contrib/stylelint/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/paul/Projects/_contrib/stylelint/node_modules/lodash/forEach.js:38:10)
    at /Users/paul/Projects/_contrib/stylelint/node_modules/table/dist/validateTableData.js:58:31
    at arrayEach (/Users/paul/Projects/_contrib/stylelint/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/paul/Projects/_contrib/stylelint/node_modules/lodash/forEach.js:38:10)
    at exports.default (/Users/paul/Projects/_contrib/stylelint/node_modules/table/dist/validateTableData.js:47:27)
    at exports.default (/Users/paul/Projects/_contrib/stylelint/node_modules/table/dist/table.js:120:35)
    at formatter (/Users/paul/Projects/_contrib/stylelint/dist/formatters/stringFormatter.js:161:33)
    at /Users/paul/Projects/_contrib/stylelint/dist/formatters/stringFormatter.js:12:15
$ cat test.css
.Test,
.Test1, {
  width: auto;
}
```

**Comment by evilebottnawi** [comment]
@ohskylab thanks i found problem place.

**Comment by evilebottnawi** [comment]
@davidtheclark https://github.com/gajus/table/blob/master/src/validateTableData.js#L43 problems here, `stylehack` return string contain newline (`cleanedMessage`):
```shell
[ [ 1,
    1,
    '\u001b[31m\u001b[31m✖\u001b[31m\u001b[39m',
    'Unexpected selector hack ".Test,\n.Test1," ', // newline here
    '\u001b[90mno-browser-hacks\u001b[39m' ] ]
```

**Comment by evilebottnawi** [comment]
@davidtheclark what do you think it is bug `stylehacks` or we should remove newlines from message in `stringFormatter`?

**Comment by evilebottnawi** [comment]
Done in https://github.com/stylelint/stylelint/pull/1253.

**Comment by jitendravyas** [comment]
I'm getting same error when I try to use https://github.com/ccbikai/stylelint-formatter-table
