### ISSUE TITLE
Unexpected token :

### ISSUE THREAD

**Issue by mikeerickson** [stylelint/stylelint#1263]
I am receiving the following error (verbose message)  Perhaps a

```
$ stylelint init    // create a bare bones default file which works
```

Note: I have also tried with

```
{
  "extend": "stylelint-config-standard"
  "rules": {}
}
```

```

SyntaxError: Unexpected token :
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at requireFromString (/home/merickson/.nvm/versions/node/v5.9.0/lib/node_modules/stylelint/node_modules/require-from-string/index.js:27:4)
    at /home/merickson/.nvm/versions/node/v5.9.0/lib/node_modules/stylelint/node_modules/cosmiconfig/lib/loadJs.js:20:15
```

In case you want me .stylelintrc, here you go

```
{
  "rules": {
    "at-rule-empty-line-before": "always",
    "at-rule-no-vendor-prefix": true,
    "block-closing-brace-newline-after": "always",
    "block-closing-brace-newline-before": "always-multi-line",
    "block-closing-brace-space-after": "always-single-line",
    "block-closing-brace-space-before": "always",
    "block-no-empty": true,
    "block-opening-brace-newline-after": "always-multi-line",
    "block-opening-brace-newline-before": "always-multi-line",
    "block-opening-brace-space-after": "always",
    "block-opening-brace-space-before": "always",
    "color-hex-case": "lower",
    "color-hex-length": "long",
    "color-no-hex": false,
    "color-no-invalid-hex": true,
    "color-no-named": true,
    "comment-empty-line-before": "always",
    "comment-whitespace-inside": "always",
    "declaration-bang-space-after": "never",
    "declaration-bang-space-before": "always",
    "declaration-block-no-single-line": false,
    "declaration-block-semicolon-newline-after": "always",
    "declaration-block-semicolon-newline-before": "never-multi-line",
    "declaration-block-semicolon-space-after": "always-single-line",
    "declaration-block-semicolon-space-before": "never-single-line",
    "declaration-block-single-line-max-declarations": 1,
    "declaration-colon-newline-after": "always-multi-line",
    "declaration-colon-space-after": "always",
    "declaration-colon-space-before": "never",
    "declaration-no-important": true,
    "function-calc-no-unspaced-operator": true,
    "function-comma-newline-after": "never-multi-line",
    "function-comma-newline-before": "never-multi-line",
    "function-comma-space-after": "always-single-line",
    "function-comma-space-before": "never",
    "function-linear-gradient-no-nonstandard-direction": true,
    "function-parentheses-newline-inside": "always-multi-line",
    "function-parentheses-space-inside": "never",
    "function-url-quotes": "double",
    "function-whitespace-after": "always",
    "indentation": 4,
    "max-empty-lines": 2,
    "max-line-length": 80,
    "media-feature-colon-space-after": "always",
    "media-feature-colon-space-before": "never",
    "media-feature-name-no-vendor-prefix": true,
    "media-feature-range-operator-space-after": "always",
    "media-feature-range-operator-space-before": "always",
    "media-query-list-comma-newline-after": "always-multi-line",
    "media-query-list-comma-newline-before": "never-multi-line",
    "media-query-list-comma-space-after": "always-single-line",
    "media-query-list-comma-space-before": "never",
    "media-query-parentheses-space-inside": "always",
    "no-eol-whitespace": true,
    "no-missing-eof-newline": true,
    "number-leading-zero": "always",
    "number-max-precision": 2,
    "number-no-trailing-zeros": true,
    "number-zero-length-no-unit": true,
    "property-no-vendor-prefix": true,
    "rule-nested-empty-line-before": "always-multi-line",
    "rule-no-duplicate-properties": true,
    "rule-no-shorthand-property-overrides": true,
    "rule-non-nested-empty-line-before": "always",
    "rule-trailing-semicolon": "always",
    "selector-combinator-space-after": "always",
    "selector-combinator-space-before": "always",
    "selector-list-comma-newline-after": "always-multi-line",
    "selector-list-comma-newline-before": "never-multi-line",
    "selector-list-comma-space-after": "always",
    "selector-list-comma-space-before": "never",
    "selector-no-id": false,
    "selector-no-type": false,
    "selector-no-universal": true,
    "selector-no-vendor-prefix": true,
    "selector-pseudo-element-colon-notation": "double",
    "selector-root-no-composition": true,
    "string-quotes": "double",
    "value-list-comma-newline-after": "always-multi-line",
    "value-list-comma-newline-before": "never-multi-line",
    "value-list-comma-space-after": "always-single-line",
    "value-list-comma-space-before": "never",
    "value-no-vendor-prefix": true
  }
}
````

I have also tried using 

```
{
  "extend": "stylelint-config-standard"
  "rules": {}
}
```

**Comment by davidtheclark** [comment]
You need a comma after "stylelint-config-standard", right?

**Comment by evilebottnawi** [comment]
@mikeerickson please give css example

**Comment by mikeerickson** [comment]
Right!  I need to have run this through a json validation

Secondly, still think the idea of a `stylelint init` and have sensible defaults (which work out of the box)

**Comment by davidtheclark** [comment]
Are you thinking `stylelint init` would, like, just produce the JSON from `stylelint-config-standard` (which represents what we think are sensible defaults)?

**Comment by mikeerickson** [comment]
@davidtheclark Yes, that would be a good addition.  I am "thinking" 

```
$ npm install stylelint (optional stylelint-loader)
$ stylelint init
```
This would create a basic default config file which contains the most sensible defaults

Users could alternately extend with something like

```
$ npm install stylelint-config-standard
```

Just a thought, could surely help with what appears to be very common issue (errors in .stylelintrc files)
And, if you want to make it even better (during init) provide option to include the above module

**Comment by davidtheclark** [comment]
Interesting idea. If you want to raise it to other maintainers, feel free to open a feature request issue.

**Comment by mikeerickson** [comment]
@davidtheclark 

>> Interesting idea. If you want to raise it to other maintainers, feel free to open a feature request issue.

Would you take a PR for it?

**Comment by davidtheclark** [comment]
I'd suggest opening an issue first so there's some period for discussion.

**Comment by mikeerickson** [comment]
@davidtheclark Will do...
