### ISSUE TITLE
`TypeError: Cannot read property 'some' of undefined`

### ISSUE THREAD

**Issue by EvNaverniouk** [stylelint/stylelint#1348]
Using the following config: https://www.npmjs.com/package/stylelint-config-cumul8 and LESS files, we are getting this error when parsing any functions:

```
TypeError: Cannot read property 'some' of undefined
    at /myproject/node_modules/stylelint/dist/rules/selector-max-compound-selectors/index.js:50:21
    at /myproject/node_modules/postcss/lib/container.js:110:28
    at /myproject/node_modules/postcss/lib/container.js:73:26
    at Rule.each (/myproject/node_modules/postcss/lib/container.js:60:22)
    at Rule.walk (/myproject/node_modules/postcss/lib/container.js:72:21)
    at /myproject/node_modules/postcss/lib/container.js:75:32
    at Rule.each (/myproject/node_modules/postcss/lib/container.js:60:22)
    at Rule.walk (/myproject/node_modules/postcss/lib/container.js:72:21)
    at /myproject/node_modules/postcss/lib/container.js:75:32
    at Root.each (/myproject/node_modules/postcss/lib/container.js:60:22)
```

A sample file that causes this:

```
.setFont(@size) {
	font-size: @size;
}

.test {
    .setFont(12px)
}
```

**Comment by ntwb** [comment]
Confirmed:
```shell
$ stylelint --config index-cumul8.js --syntax less test.less
TypeError: Cannot read property 'some' of undefined
    at /usr/local/lib/node_modules/stylelint/dist/rules/selector-max-compound-selectors/index.js:50:21
    at /usr/local/lib/node_modules/stylelint/node_modules/postcss/lib/container.js:118:28
    at /usr/local/lib/node_modules/stylelint/node_modules/postcss/lib/container.js:81:26
    at Rule.each (/usr/local/lib/node_modules/stylelint/node_modules/postcss/lib/container.js:68:22)
    at Rule.walk (/usr/local/lib/node_modules/stylelint/node_modules/postcss/lib/container.js:80:21)
    at /usr/local/lib/node_modules/stylelint/node_modules/postcss/lib/container.js:83:32
    at Root.each (/usr/local/lib/node_modules/stylelint/node_modules/postcss/lib/container.js:68:22)
    at Root.walk (/usr/local/lib/node_modules/stylelint/node_modules/postcss/lib/container.js:80:21)
    at Root.walkRules (/usr/local/lib/node_modules/stylelint/node_modules/postcss/lib/container.js:116:25)
    at /usr/local/lib/node_modules/stylelint/dist/rules/selector-max-compound-se
```

Removing the `selector-max-compound-selectors` rule from the config results as expected:
```shell
$ stylelint --config index-cumul8.js --syntax less test.less 

test.less
 2:5  ✖  Expected indentation of 1 tab   indentation
 6:5  ✖  Expected indentation of 1 tab   indentation
```
