### ISSUE TITLE
TypeError: vars.includes is not a function

### ISSUE THREAD

**Issue by reintroducing** [stylelint/stylelint#1395]
I'm trying to lint my codebase and I'm running into an issue from one of my files that has nothing but sass variables in it.  I've dumbed down the file to just one variable declaration and its still causing the following error:

```
TypeError: vars.includes is not a function
    at /Users/przybylski/retrofit/dev/code/client-dashboard/node_modules/stylelint-scss/dist/rules/dollar-variable-no-missing-interpolation/index.js:24:38
    at /Users/przybylski/.nvm/versions/node/v4.4.5/lib/node_modules/stylelint/node_modules/postcss/lib/container.js:94:28
    at /Users/przybylski/.nvm/versions/node/v4.4.5/lib/node_modules/stylelint/node_modules/postcss/lib/container.js:81:26
    at Root.each (/Users/przybylski/.nvm/versions/node/v4.4.5/lib/node_modules/stylelint/node_modules/postcss/lib/container.js:68:22)
    at Root.walk (/Users/przybylski/.nvm/versions/node/v4.4.5/lib/node_modules/stylelint/node_modules/postcss/lib/container.js:80:21)
    at Root.walkDecls (/Users/przybylski/.nvm/versions/node/v4.4.5/lib/node_modules/stylelint/node_modules/postcss/lib/container.js:92:25)
    at findVars (/Users/przybylski/retrofit/dev/code/client-dashboard/node_modules/stylelint-scss/dist/rules/dollar-variable-no-missing-interpolation/index.js:19:12)
    at /Users/przybylski/retrofit/dev/code/client-dashboard/node_modules/stylelint-scss/dist/rules/dollar-variable-no-missing-interpolation/index.js:36:5
    at /Users/przybylski/.nvm/versions/node/v4.4.5/lib/node_modules/stylelint/dist/postcssPlugin.js:131:67
    at Array.forEach (native)
```

My file consists of just this:
```
$path-img: "../img/";
```

There was a bunch of other stuff in there but I took it out for demo purposes. The command I'm running is this:

```
stylelint "sass/utils/_defaults.scss" --syntax scss
```

Am I missing something or is this indeed an issue?  If I ignore that file and run stylelint on the rest of my code it works (for the most part, it also doesn't seem to like sass functions, I can give more detail on that if you'd like).

Any help would be appreciated.

**Comment by reintroducing** [comment]
Ugh, literally right after I wrote this I looked at this closer and realized the scss rule causing this. Sorry for wasting anyone's time :)
