### ISSUE TITLE
A bug where run cli on OSX and within iTerm2. "Error: Column width must be greater than 0."

### ISSUE THREAD

**Issue by ltchronus** [stylelint/stylelint#1473]
Have ran stylelint(v6.6.0) cli on OSX with iTerm2.
```
stylelint *.css
```
It failed with info blow 
```
Error: Column width must be greater than 0.
    at exports.default (/Users/ltchronus/Documents/workspace4air/developer/node_modules/table/dist/calculateCellHeight.js:48:15)
    at /Users/ltchronus/Documents/workspace4air/developer/node_modules/table/dist/calculateRowHeightIndex.js:63:73
    at arrayEach (/Users/ltchronus/Documents/workspace4air/developer/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/ltchronus/Documents/workspace4air/developer/node_modules/lodash/forEach.js:38:10)
    at /Users/ltchronus/Documents/workspace4air/developer/node_modules/table/dist/calculateRowHeightIndex.js:54:31
    at arrayEach (/Users/ltchronus/Documents/workspace4air/developer/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/ltchronus/Documents/workspace4air/developer/node_modules/lodash/forEach.js:38:10)
    at exports.default (/Users/ltchronus/Documents/workspace4air/developer/node_modules/table/dist/calculateRowHeightIndex.js:49:27)
    at exports.default (/Users/ltchronus/Documents/workspace4air/developer/node_modules/table/dist/table.js:128:58)
```
After debugging for a while, I found that getMessageWidth() returns a negative number. Maybe the reason is that I was using three columns of panes in split view iTerm2 which results in a small process.stdout.columns value. #1405

**Comment by ltchronus** [comment]
@jeddy3 the function is in line 50 of stylelint/src/formatters/stringFormatter.js

**Comment by jeddy3** [comment]
@ltchronus Thanks for writing up the issue. We've plans to shore-up the formatters with better tests. Hopefully this will get resolved along with that.

Related issue: https://github.com/stylelint/stylelint/issues/1405
Related shoring-up of tests: https://github.com/stylelint/stylelint/issues/1359
