### ISSUE TITLE
declaration-bang-space-after issue

### ISSUE THREAD

**Issue by killanaca** [stylelint/stylelint#1905]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug where

> Which rule, if any, is this issue related to?

`declaration-bang-space-after`

> What CSS is needed to reproduce this issue?

```css
body{
  background: red;
}
```

> What stylelint configuration is needed to reproduce this issue?

```json
{
	"ignoreFiles": "node_modules",
  "rules": {
		"declaration-bang-space-after": "always"
  }
}
```

but also
```json
{
	"ignoreFiles": "node_modules",
  "rules": {
		"declaration-bang-space-after": "never"
  }
}
```

> Which version of stylelint are you using?

`7.2.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

like PostCSS plugin

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

no

> What did you expect to happen?

"No warnings to be flagged."

> What actually happened (e.g. what warnings or errors you are getting)?

```shell
[15:55:39]  unhandledRejection TypeError: Cannot read property 'length' of undefined
    at exports.default (C:\Users\user\Documents\pm\deployment-tools\node_modules\stylelint\dist\utils\declarationValueIndex.js:9:39)
    at C:\Users\user\Documents\pm\deployment-tools\node_modules\stylelint\dist\rules\declaration-bang-space-after\index.js:56:56
    at C:\Users\user\Documents\pm\deployment-tools\node_modules\postcss\lib\container.js:207:28
    at C:\Users\user\Documents\pm\deployment-tools\node_modules\postcss\lib\container.js:163:26
    at Rule.each (C:\Users\user\Documents\pm\deployment-tools\node_modules\postcss\lib\container.js:129:22)
    at Rule.walk (C:\Users\user\Documents\pm\deployment-tools\node_modules\postcss\lib\container.js:162:21)
    at C:\Users\user\Documents\pm\deployment-tools\node_modules\postcss\lib\container.js:165:32
    at Root.each (C:\Users\user\Documents\pm\deployment-tools\node_modules\postcss\lib\container.js:129:22)
    at Root.walk (C:\Users\user\Documents\pm\deployment-tools\node_modules\postcss\lib\container.js:162:21)
    at Root.walkDecls (C:\Users\user\Documents\pm\deployment-tools\node_modules\postcss\lib\container.js:205:25)
    at declarationBangSpaceChecker (C:\Users\user\Documents\pm\deployment-tools\node_modules\stylelint\dist\rules\declaration-bang-space-after\index.js:55:8)
    at C:\Users\user\Documents\pm\deployment-tools\node_modules\stylelint\dist\rules\declaration-bang-space-after\index.js:19:5
    at C:\Users\user\Documents\pm\deployment-tools\node_modules\stylelint\dist\postcssPlugin.js:124:46
    at Array.forEach (native)
    at C:\Users\user\Documents\pm\deployment-tools\node_modules\stylelint\dist\postcssPlugin.js:103:33 Promise {
  <rejected> TypeError: Cannot read property 'length' of undefined
    at exports.default (C:\Users\user\Documents\pm\deployment-tools\node_modules\stylelint\dist\utils\declarationValueIndex.js:9:39)
    at C:\Users\user\Documents\pm\deployment-tools\node_modules\stylelint\dist\rules\declaration-bang-space-after\index.js:56:56
    at C:\Users\user\Documents\pm\deployment-tools\node_modules\postcss\lib\container.js:207:28
    at C:\Users\user\Documents\pm\deployment-tools\node_modules\postcss\lib\container.js:163:26
    at Rule.each (C:\Users\user\Documents\pm\deployment-tools\node_modules\postcss\lib\container.js:129:22)
    at Rule.walk (C:\Users\user\Documents\pm\deployment-tools\node_modules\postcss\lib\container.js:162:21)
    at C:\Users\user\Documents\pm\deployment-tools\node_modules\postcss\lib\container.js:165:32
    at Root.each (C:\Users\user\Documents\pm\deployment-tools\node_modules\postcss\lib\container.js:129:22)
    at Root.walk (C:\Users\user\Documents\pm\deployment-tools\node_modules\postcss\lib\container.js:162:21)
    at Root.walkDecls (C:\Users\user\Documents\pm\deployment-tools\node_modules\postcss\lib\container.js:205:25)
    at declarationBangSpaceChecker (C:\Users\user\Documents\pm\deployment-tools\node_modules\stylelint\dist\rules\declaration-bang-space-after\index.js:55:8)
    at C:\Users\user\Documents\pm\deployment-tools\node_modules\stylelint\dist\rules\declaration-bang-space-after\index.js:19:5
    at C:\Users\user\Documents\pm\deployment-tools\node_modules\stylelint\dist\postcssPlugin.js:124:46
    at Array.forEach (native)
    at C:\Users\user\Documents\pm\deployment-tools\node_modules\stylelint\dist\postcssPlugin.js:103:33 }
```

**Comment by evilebottnawi** [comment]
@killanaca very strange behaviour, can you create repo with reproduced errors?
BTW, node version?

**Comment by killanaca** [comment]
node version is 6.5.0 
the problem could be relative to some postcss plugins?
I use stylelint in a [project](https://github.com/killanaca/deployment-tools) as [postcss plugins](https://github.com/killanaca/deployment-tools/blob/master/src/utils/css.js#L93) with some others postcss plugins

**Comment by davidtheclark** [comment]
@killanaca Please stylelint *before* other PostCSS plugins. Preferably, run it via the CLI or Node API rather than as a Gulp plugin. I believe your issue is certainly related to that.

If it still doesn't work for you, please open an issue with a test case that demonstrates the bug. Thanks!
