### ISSUE TITLE
sass syntax 

### ISSUE THREAD

**Issue by theskillwithin** [stylelint/stylelint#1937]
new feature supporting both sass and scss syntax with tabs.    in cli.

**Comment by ntwb** [comment]
Thanks for creating this issue but we are closing it as issues need to follow our issue template, so that we can clearly understand your particular circumstances.

Please help us to help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new) using the template.

**Comment by theskillwithin** [comment]
@ntwb 

using sublime text on .sass file  (also linter settings below).    also didn't work when I tried in cli also.


```
SublimeLinter: scss output:
/Users/Austin/.rvm/rubies/ruby-2.3.0/bin/ruby: No such file or directory -- scss-lint (LoadError) 
SublimeLinter: stylelint: _page-home.sass ['/usr/local/bin/node', '/Users/Austin/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-contrib-stylelint/stylelint_wrapper.js', '@'] 
SublimeLinter: stylelint output:
CssSyntaxError: /var/folders/q8/4rj_3ly11hqd4fx7tw6tfssc0000gn/T/SublimeLinter3-Austin/_page-home.sass:4:1: Missed semicolon
    at Input.error (/Users/Austin/node_modules/postcss/lib/input.js:120:22)
    at Parser.checkMissedSemicolon (/Users/Austin/node_modules/postcss/lib/parser.js:495:26)
    at Parser.decl (/Users/Austin/node_modules/postcss/lib/parser.js:270:50)
    at Parser.other (/Users/Austin/node_modules/postcss/lib/parser.js:170:18)
    at Parser.loop (/Users/Austin/node_modules/postcss/lib/parser.js:81:26)
    at parse (/Users/Austin/node_modules/postcss/lib/parse.js:26:16)
    at new LazyResult (/Users/Austin/node_modules/postcss/lib/lazy-result.js:80:24)
    at Processor.process (/Users/Austin/node_modules/postcss/lib/processor.js:200:12)
    at Object.<anonymous> (/Users/Austin/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-contrib-stylelint/stylelint_wrapper.js:85:10)
    at Module._compile (module.js:556:32) 
SublimeLinter: scss: _grid.sass ['/Users/Austin/.rvm/rubies/ruby-2.3.0/bin/ruby', '-S', 'scss-lint'] 
SublimeLinter: scss output:
/Users/Austin/.rvm/rubies/ruby-2.3.0/bin/ruby: No such file or directory -- scss-lint (LoadError) 
SublimeLinter: stylelint: _grid.sass ['/usr/local/bin/node', '/Users/Austin/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-contrib-stylelint/stylelint_wrapper.js', '@'] 
using gpu buffer for window
SublimeLinter: stylelint output:
CssSyntaxError: /var/folders/q8/4rj_3ly11hqd4fx7tw6tfssc0000gn/T/SublimeLinter3-Austin/_grid.sass:1:13: Missed semicolon
    at Input.error (/Users/Austin/node_modules/postcss/lib/input.js:120:22)
    at Parser.checkMissedSemicolon (/Users/Austin/node_modules/postcss/lib/parser.js:495:26)
    at Parser.decl (/Users/Austin/node_modules/postcss/lib/parser.js:270:50)
    at Parser.other (/Users/Austin/node_modules/postcss/lib/parser.js:170:18)
    at Parser.loop (/Users/Austin/node_modules/postcss/lib/parser.js:81:26)
    at parse (/Users/Austin/node_modules/postcss/lib/parse.js:26:16)
    at new LazyResult (/Users/Austin/node_modules/postcss/lib/lazy-result.js:80:24)
    at Processor.process (/Users/Austin/node_modules/postcss/lib/processor.js:200:12)
    at Object.<anonymous> (/Users/Austin/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-contrib-stylelint/stylelint_wrapper.js:85:10)
    at Module._compile (module.js:556:32) 
SublimeLinter: stylelint: _footer.sass ['/usr/local/bin/node', '/Users/Austin/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-contrib-stylelint/stylelint_wrapper.js', '@'] 
SublimeLinter: stylelint output:
CssSyntaxError: /var/folders/q8/4rj_3ly11hqd4fx7tw6tfssc0000gn/T/SublimeLinter3-Austin/_footer.sass:9:2: Missed semicolon
    at Input.error (/Users/Austin/node_modules/postcss/lib/input.js:120:22)
    at Parser.checkMissedSemicolon (/Users/Austin/node_modules/postcss/lib/parser.js:495:26)
    at Parser.decl (/Users/Austin/node_modules/postcss/lib/parser.js:270:50)
    at Parser.other (/Users/Austin/node_modules/postcss/lib/parser.js:170:18)
    at Parser.loop (/Users/Austin/node_modules/postcss/lib/parser.js:81:26)
    at parse (/Users/Austin/node_modules/postcss/lib/parse.js:26:16)
    at new LazyResult (/Users/Austin/node_modules/postcss/lib/lazy-result.js:80:24)
    at Processor.process (/Users/Austin/node_modules/postcss/lib/processor.js:200:12)
    at Object.<anonymous> (/Users/Austin/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-contrib-stylelint/stylelint_wrapper.js:85:10)
    at Module._compile (module.js:556:32) 
SublimeLinter: scss: _footer.sass ['/Users/Austin/.rvm/rubies/ruby-2.3.0/bin/ruby', '-S', 'scss-lint'] 
SublimeLinter: scss output:
/Users/Austin/.rvm/rubies/ruby-2.3.0/bin/ruby: No such file or directory -- scss-lint (LoadError) 
SublimeLinter: puglint: _footer.pug ['/usr/local/bin/pug-lint', '@', '--reporter=inline'] 
SublimeLinter: scss: _grid.sass ['/Users/Austin/.rvm/rubies/ruby-2.3.0/bin/ruby', '-S', 'scss-lint'] 
SublimeLinter: scss output:
/Users/Austin/.rvm/rubies/ruby-2.3.0/bin/ruby: No such file or directory -- scss-lint (LoadError) 
SublimeLinter: stylelint: _grid.sass ['/usr/local/bin/node', '/Users/Austin/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-contrib-stylelint/stylelint_wrapper.js', '@'] 
SublimeLinter: stylelint output:
CssSyntaxError: /var/folders/q8/4rj_3ly11hqd4fx7tw6tfssc0000gn/T/SublimeLinter3-Austin/_grid.sass:1:13: Missed semicolon
    at Input.error (/Users/Austin/node_modules/postcss/lib/input.js:120:22)
    at Parser.checkMissedSemicolon (/Users/Austin/node_modules/postcss/lib/parser.js:495:26)
    at Parser.decl (/Users/Austin/node_modules/postcss/lib/parser.js:270:50)
    at Parser.other (/Users/Austin/node_modules/postcss/lib/parser.js:170:18)
    at Parser.loop (/Users/Austin/node_modules/postcss/lib/parser.js:81:26)
    at parse (/Users/Austin/node_modules/postcss/lib/parse.js:26:16)
    at new LazyResult (/Users/Austin/node_modules/postcss/lib/lazy-result.js:80:24)
    at Processor.process (/Users/Austin/node_modules/postcss/lib/processor.js:200:12)
    at Object.<anonymous> (/Users/Austin/Library/Application Support/Sublime Text 3/Packages/SublimeLinter-contrib-stylelint/stylelint_wrapper.js:85:10)
    at Module._compile (module.js:556:32) 
```



linter settings
```
"linters": {
            "csslint": {
                "@disable": false,
                "args": [],
                "errors": "",
                "excludes": [],
                "ignore": "",
                "warnings": ""
            },
            "phplint": {
                "@disable": false,
                "args": [],
                "excludes": []
            },
            "puglint": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "reporter": "inline"
            },
            "sass": {
                "@disable": true,
                "args": [],
                "excludes": []
            },
            "scss": {
                "@disable": false,
                "args": [],
                "exclude-linter": "",
                "excludes": [],
                "include-linter": ""
            },
            "stylelint": {
                "@disable": false,
                "args": [],
                "excludes": []
            }
        },
```
