### ISSUE TITLE
Set is not defined error when requiring stylelint

### ISSUE THREAD

**Issue by isochronous** [stylelint/stylelint#1954]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug where I cannot even `require('stylelint')` without getting a fatal exception.

> Which rule, if any, is this issue related to?

Not related to any rule

> What CSS is needed to reproduce this issue?

none

> What stylelint configuration is needed to reproduce this issue?

none

> Which version of stylelint are you using?

`7.3.1`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Currently using gulp-stylelint, but the same issue occurs if I try to `var stylelint = require('stylelint');` or `var stylelint = require('postcss-stylelint');`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

To not get an error by simply requiring the library

> What actually happened (e.g. what warnings or errors you are getting)?

This is the error I get whenever I try to require stylelint or any lib that uses stylelint.

```
ReferenceError: Set is not defined
    at Object.<anonymous> (D:\Projects\AI\main\somePath\node_modules\stylelint\dist\reference\keywordSets.js:14:51)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\Projects\AI\main\somePath\node_modules\stylelint\dist\utils\findAnimationName.js:8:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

This is on a windows machine, btw.  The problem occurs using both node v4.6.0 and v6.7.0.  Let me know if you'd like more details.

**Comment by evilebottnawi** [comment]
@isochronous nodejs version?

**Comment by evilebottnawi** [comment]
@isochronous can you try in your app/library `console.dir(Set)`?

**Comment by isochronous** [comment]
```
ReferenceError: Set is not defined
    at Gulp.docs (D:\Projects\AI\main\somePath\gulpfile.js:118:17)
    at module.exports (D:\Projects\AI\main\somePath\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\Projects\AI\main\somePath\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\Projects\AI\main\somePath\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\Projects\AI\main\somePath\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at C:\Users\me\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by evilebottnawi** [comment]
@isochronous try `console.log(`Version: ${process.version}`);`

**Comment by davidtheclark** [comment]
@isochronous: If `Set` is not defined it really seems like your not running the Node version you think you're running.

**Comment by isochronous** [comment]
Yeah, it looks like someone checked in some standalone version of node in that directory without my noticing.  Once I got rid of that, everything worked as expected.  Sorry to take up your time!
