### ISSUE TITLE
Random CI failures and slowdowns in Jest tests

### ISSUE THREAD

**Issue by davidtheclark** [stylelint/stylelint#2131]
I'm seeing some problems with the Jest tests that are bumming me out ... (ಠ_ಠ)

Occasionally, not consistently, async tests are timing out with an error like this:

```

 FAIL  src/rules/block-closing-brace-newline-after/__tests__/index.js (100.175s)
  ● block-closing-brace-newline-after › reject › no description
    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at ontimeout (timers.js:365:14)
      at tryOnTimeout (timers.js:237:5)
      at Timer.listOnTimeout (timers.js:207:5)
```

Such tests may or may not pass on a retry.

Also, I'm seeing a lot of hang time slowing down Travis. Throughout the suite listing there are messages like this:

```
PASS  src/rules/declaration-block-properties-order/__tests__/grouped-strict.js (76.282s)
```

So running the tests in that one file ended up taking 76 seconds? That's a significant problem.

I can't reproduce these problems locally, and don't see problems with the code suggesting that we're not handling async right (e.g. never resolving a Promise). Maybe I'm missing something ...

Anyway, this needs more investigation. I'm beginning to regret our trial of the hot new thing ... (ಠ⌣ಠ)

**Comment by davidtheclark** [comment]
Running with the `-i` flag prevented the timeout errors, as 

BUT I still was unable to finish running the tests successfully. Hit an allocation failure:

```

<--- Last few GCs --->

[2473:0x3109a00]   341803 ms: Mark-sweep 1404.1 (1532.0) -> 1404.1 (1532.0) MB, 1353.1 / 0.0 ms  allocation failure GC in old space requested
[2473:0x3109a00]   343219 ms: Mark-sweep 1404.1 (1532.0) -> 1404.1 (1531.0) MB, 1414.9 / 0.0 ms  last resort gc 
[2473:0x3109a00]   344601 ms: Mark-sweep 1404.1 (1531.0) -> 1404.1 (1531.0) MB, 1381.7 / 0.0 ms  last resort gc 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2ebae67c0d31 <JS Object>
    2: Int16ArrayConstructByIterable(aka Int16ArrayConstructByIterable) [native typedarray.js:1] [pc=0x24e30ac2856](this=0x2ebae6704311 <undefined>,ad=0x215fd6136bd9 <an Int16Array with map 0x3dda14051eb9>,ap=0x215fd6136b59 <JS Array[1]>,aq=0xfb76a71e939 <JS Function arr.(anonymous function) (SharedFunctionInfo 0x350360bf011)>)
    3: new constructor(aka Int16Array) [native typedarray.js:1] [pc...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x126492c [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::CopyFixedArrayAndGrow(v8::internal::Handle<v8::internal::FixedArray>, int, v8::internal::PretenureFlag) [node]
 6: v8::internal::SharedFunctionInfo::AddToOptimizedCodeMap(v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::Context>, v8::internal::MaybeHandle<v8::internal::Code>, v8::internal::Handle<v8::internal::LiteralsArray>, v8::internal::BailoutId) [node]
 7: v8::internal::SharedFunctionInfo::FindOrCreateLiterals(v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::Context>) [node]
 8: v8::internal::JSFunction::EnsureLiterals(v8::internal::Handle<v8::internal::JSFunction>) [node]
 9: v8::internal::Compiler::Compile(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag) [node]
10: v8::internal::Runtime_CompileLazy(int, v8::internal::Object**, v8::internal::Isolate*) [node]
11: 0x24e2e3063a7
Aborted (core dumped)
```

**Comment by davidtheclark** [comment]
Also worth noting that the ^^ memory failure occurred *5.5 minutes* into running the tests ... so perf is still not acceptable for us.

**Comment by evilebottnawi** [comment]
@davidtheclark have some issue in other project, i think trouble in `jest`, need investigation and `issue` in `ject`

**Comment by davidtheclark** [comment]
@evilebottnawi There is a relevant closed issue in Jest: https://github.com/facebook/jest/issues/1742. And I opened a new whiny issue: https://github.com/facebook/jest/issues/2171

**Comment by davidtheclark** [comment]
We've tracked this down, done what we can, and opened relevant issues. So I'm going to close this particular issue.
