### ISSUE TITLE
CLI with globs not working correctly?

### ISSUE THREAD

**Issue by reintroducing** [stylelint/stylelint#2202]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

I'm running stylelint through the CLI and I'm getting an error:
```shell
./node_modules/.bin/stylelint "frontend/src/sass/**/*.scss"
TypeError: Cannot read property 'isCalculationEnabled' of undefined
    at findOperators (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/stylelint-scss/dist/utils/sassValueParser/index.js:79:36)
    at /Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/stylelint-scss/dist/rules/operator-no-unspaced/index.js:192:47
    at /Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/stylelint/node_modules/postcss/lib/container.js:148:26
    at AtRule.each (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/stylelint/node_modules/postcss/lib/container.js:114:22)
    at AtRule.walk (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/stylelint/node_modules/postcss/lib/container.js:147:21)
    at /Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/stylelint/node_modules/postcss/lib/container.js:150:32
    at AtRule.each (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/stylelint/node_modules/postcss/lib/container.js:114:22)
    at AtRule.walk (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/stylelint/node_modules/postcss/lib/container.js:147:21)
    at /Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/stylelint/node_modules/postcss/lib/container.js:150:32
    at AtRule.each (/Users/mprzybylski/Work/SpotHero/SpotHero-Django/node_modules/stylelint/node_modules/postcss/lib/container.js:114:22)
```

When I run one directory deeper, it works as expected:
```shell
./node_modules/.bin/stylelint "frontend/src/sass/components/*.scss"
```

> Which rule, if any, is this issue related to?

Unrelated to a rule as far as I can tell.

> What CSS is needed to reproduce this issue?

N/A

> What stylelint configuration is needed to reproduce this issue?

e.g.

Not sure this is a config related issue as it works just one directory deeper.

> Which version of stylelint are you using?

7.7.0

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI as shown above

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

My files are .scss but we just use basic functionality in sass, nothing too extensive (variables, mixins, nesting).

> What did you expect to happen?

Was expecting linter outpout in terminal like for the second command inside of the `components/` directory.

> What actually happened (e.g. what warnings or errors you are getting)?

See error above.

**Comment by reintroducing** [comment]
Disregard, this has to do with a vendor directory I have which I will not be testing anyway, my mistake, sorry for the noise.
