### ISSUE TITLE
Fix failing tests for `no-unsupported-browser-features` in AppVeyor

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint#2525]
Recently tests for `no-unsupported-browser-features` in AppVeyor started to fail.

Take a look at commits in https://github.com/stylelint/stylelint/commits/master

Why it's happening? Why it's happening on AppVeyor only? Maybe doiuse was updated, and AppVeyor installing new dependencies, while Travis use cache?

<details>
<summary>Error log:</summary>

```
FAIL  lib\rules\no-unsupported-browser-features\__tests__\index.js (6.843s)
● no-unsupported-browser-features › accept › no description
  expect(received).toEqual(expected)
  
  Expected value to equal:
    Array []
  Received:
    [{"column": 5, "line": 1, "rule": "no-unsupported-browser-features", "severity": "error", "text": "Unexpected browser feature \"outline\" is only partially supported by IE 10,11, Edge 14, IE Mobile 10,11 (no-unsupported-browser-features)"}]
  
  Difference:
  
  - Expected
  + Received
  
  -Array []
  +Array [
  +  Object {
  +    "column": 5,
  +    "line": 1,
  +    "rule": "no-unsupported-browser-features",
  +    "severity": "error",
  +    "text": "Unexpected browser feature \"outline\" is only partially supported by IE 10,11, Edge 14, IE Mobile 10,11 (no-unsupported-browser-features)",
  +  },
  +]
    
    at stylelint.then.output (jest-setup.js:53:50)
● no-unsupported-browser-features › reject › outline
  expect(received).toBe(expected)
  
  Expected value to be (using ===):
    "Unexpected browser feature \"outline\" is not supported by IE 7 (no-unsupported-browser-features)"
  Received:
    "Unexpected browser feature \"outline\" is not supported by IE 7 and only partially supported by IE 8,9,10,11 (no-unsupported-browser-features)"
    
    at stylelint.then.output (jest-setup.js:83:48)
● no-unsupported-browser-features › accept › no description
  expect(received).toEqual(expected)
  
  Expected value to equal:
    Array []
  Received:
    [{"column": 5, "line": 1, "rule": "no-unsupported-browser-features", "severity": "error", "text": "Unexpected browser feature \"outline\" is only partially supported by IE 9,10,11 (no-unsupported-browser-features)"}]
  
  Difference:
  
  - Expected
  + Received
  
  -Array []
  +Array [
  +  Object {
  +    "column": 5,
  +    "line": 1,
  +    "rule": "no-unsupported-browser-features",
  +    "severity": "error",
  +    "text": "Unexpected browser feature \"outline\" is only partially supported by IE 9,10,11 (no-unsupported-browser-features)",
  +  },
  +]
    
    at stylelint.then.output (jest-setup.js:53:50)

```

</details>

**Comment by hudochenkov** [comment]
I've checked with packages installed from scratch. Got same errors. Probably `caniuse-db`, which is used by `doiuse`, have been updated.

**Comment by jeddy3** [comment]
Done in #2526

**Comment by CAYdenberg** [comment]
For anyone else experiencing this error even after the fix, try deleting your node_modules dir and reinstalling everything with `npm install`

**Comment by evilebottnawi** [comment]
@CAYdenberg Which error?

**Comment by CAYdenberg** [comment]
"Unexpected browser feature \"outline\" is only partially supported by IE 10,11, Edge 14, IE Mobile 10,11 (no-unsupported-browser-features)"

I should probably say failing tests, not errors

**Comment by evilebottnawi** [comment]
@CAYdenberg your got this error in own CI build?

**Comment by CAYdenberg** [comment]
No I got it while running the test suite (after a fresh pull of master, today, v7.10.1) and couldn't figure out why.

**Comment by evilebottnawi** [comment]
@CAYdenberg try first `npm cache clean`, then remove `node_modules` and again `npm i`, if it is not resolve problem just ping me again
