### ISSUE TITLE
Undefined rule at-rule-semicolon-space-before

### ISSUE THREAD

**Issue by jitendravyas** [stylelint/stylelint#2598]
OSX
stylelint -v 7.8.0
https://github.com/wikimedia/grunt-stylelint/releases/tag/v0.8.0

```
❯ grunt stylelint
Running "stylelint:all" (stylelint) task
Warning: Running stylelint failed
Error: Undefined rule at-rule-semicolon-space-before
    at module.exports (/Users/jitendravyas/app-v3/node_modules/stylelint/lib/utils/configurationError.js:8:27)
    at Object.keys.forEach.ruleName (/Users/jitendravyas/app-v3/node_modules/stylelint/lib/augmentConfig.js:278:13)
    at Array.forEach (native)
    at normalizeAllRuleSettings (/Users/jitendravyas/app-v3/node_modules/stylelint/lib/augmentConfig.js:274:29)
    at augmentConfigBasic.then.then.then.then.augmentedConfig (/Users/jitendravyas/app-v3/node_modules/stylelint/lib/augmentConfig.js:83:12) Use --force to continue.
```

**Comment by hudochenkov** [comment]
Please update your stylelint to the latest version. These rule was added in [7.10.0](https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md#7100).
