### ISSUE TITLE
Latest master branch doesn't work in Node 4

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint#2607]
I was testing `stylelint-order` on latest stylelint `master` and seems like stylelint doesn't work in Node 4.

Installed locally (using [`n`](https://github.com/tj/n)) and in Travis:

```
node v4.8.3
npm 2.15.11
```

If I clone stylelint repository locally, then do `npm install` and `npm test`, then no problems. That what Travis do for us as well.

In different scenarious, when stylelint is dependency, things are getting worse.

**Scenario 1**

Jest test for stylelint-order.

**Scenario 2**

```bash
npm init
npm i github:stylelint/stylelint
node run.js
```

**Scenario 3**

```bash
npm init
npm i github:stylelint/stylelint
node_modules/.bin/stylelint test.css
```

**Scenario 4**

```bash
npm init
npm i ../stylelint # stylelint in sibling folder
node run.js
```

---

```js
// run.js
'use strict';

const stylelint = require('stylelint');

const config = {
	rules: {
		"indentation": "tab"
	},
};

stylelint.lint({
	formatter: 'string',
	code: `
		a {
			display: none;
			--width: 10px;
		}
	`,
	config,
}).then(function (data) {
	console.log(data.output);
	console.log('-----------------');
	console.log(data.results[0].warnings);
	console.log('Done.');
}, function (err) {
	console.log(err);
});
```

Every time I get this error:

```js
$ node run
module.js:327
    throw err;
    ^

Error: Cannot find module 'pify'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/aleks/Downloads/test/sdsdf/node_modules/stylelint/lib/standalone.js:3:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

I had no luck to find what is going on :( Can we add tests to detect problems like this? That tool doesn't work for users. Because we have green tests, when in fact stylelint doesn't work in Node 4. Maybe there is some kind of problem with npm@2.

Node 6 and 8 work as expected.

**Comment by hudochenkov** [comment]
Fixed in #2614.
