### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by XhmikosR** [stylelint/stylelint#2774]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

A bug or a config question

> Which rule, if any, is this issue related to?

isAutoprefixable

> What CSS is needed to reproduce this issue?

```css
.foo {
  color: pink;
}
```

> What stylelint configuration is needed to reproduce this issue?

```json
{
  "extends": "stylelint-config-standard",
  "rules": {
    "block-closing-brace-empty-line-before": null,
    "block-opening-brace-space-before": "always",
    "color-hex-length": "long",
    "color-named": "never",
    "function-parentheses-space-inside": "never",
    "function-url-quotes": "always",
    "indentation": 4,
    "max-empty-lines": 2,
    "media-query-list-comma-space-after": "always",
    "rule-empty-line-before": ["always", {
      "except": ["first-nested"],
      "ignore": ["after-comment"]
    }],
    "value-list-comma-newline-after": "never-multi-line",
    "value-list-comma-newline-before": "never-multi-line",
    "value-list-comma-space-after": "always"
  }
}
```

> Which version of stylelint are you using?

`8.0.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

PostCSS plugin with Gulp:

```js
gulp.task('lint:styles', function() {
    return gulp.src(config.lintStyles.src)
        .pipe(postcss([
            stylelint(),
            reporter(config.lintStyles.options.reporter)
        ], { syntax: sassParser }));
});
```

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No

> What did you expect to happen?

Stylelint should run

> What actually happened (e.g. what warnings or errors you are getting)?

```shell
C:\Users\xmr\Desktop\foo>gulp lint:styles
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:207:7)
    at eachParent (C:\Users\xmr\Desktop\foo\node_modules\browserslist\index.js:65:18)
    at getStat (C:\Users\xmr\Desktop\foo\node_modules\browserslist\index.js:79:12)
    at browserslist (C:\Users\xmr\Desktop\foo\node_modules\browserslist\index.js:188:15)
    at Browsers.parse (C:\Users\xmr\Desktop\foo\node_modules\autoprefixer\lib\browsers.js:61:16)
    at new Browsers (C:\Users\xmr\Desktop\foo\node_modules\autoprefixer\lib\browsers.js:52:30)
    at Object.<anonymous> (C:\Users\xmr\Desktop\foo\node_modules\stylelint\lib\utils\isAutoprefixable.js:19:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)

```

This isn't a bug (probably), but I keep getting the aforementioned TypeError with v8.0.0. I tried adding a `.browserslistrc` file but I still get the same. Does stylelint need a path to the `.browserslistrc` file?

Going back to v7.11.1 works but I guess it's because the autoprefixer rule isn't implemented there.

Thanks in advance!

**Comment by XhmikosR** [comment]
Nevermind, I get this regardless of the stylelint version so I guess it's autoprefixer itself that's causing this.
