### ISSUE TITLE
Cannot find module specificity, postcss-less, postcss-scss

### ISSUE THREAD

**Issue by willdavidow** [stylelint/stylelint#2782]
I just installed stylelint and the stylelint-scss plugin, and have a very simple rules file set up... Upon running stylelint against my source directory I have a few 'cannot find module errors:

I have `stylelint` installed globally, and `stylelint-config-recommend`, `stylelint-scss` and `stylelint-selector-bem-pattern` installed as dev dependencies within my `package.json`

Here is my `.stylelintrc` file:

```json
{
  "configBaseDir": "./",
  "ignoreFiles": [
    "dist/**/*",
    "node_modules/**/*"
  ],
  "extends": "stylelint-config-recommended",
  "plugins": [
    "stylelint-scss",
    "stylelint-selector-bem-pattern"
  ],
  "rules": {
    "at-rule-no-unknown": [ true, {
      "ignoreAtRules": [
        "extends"
      ]
    }],
    "block-no-empty": null,
    "unit-whitelist": [
      "%",
      "deg",
      "em",
      "ms",
      "px",
      "rem",
      "s",
      "vh",
      "vw"
    ]
  }
}

```

```
zsh: stylelint "src/**/*.scss"
```

Resulting in the following:
```
Error: Cannot find module 'specificity'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/project/node_modules/stylelint/lib/rules/no-descending-specificity/index.js:3:21)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

I then ran `npm i specificity` and re-ran `zsh: stylelint "src/**/*.scss"`

Resulting in the following:
```
Error: Cannot find module 'postcss-less'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/project/node_modules/stylelint/lib/testUtils/createRuleTester.js:6:20)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

I then ran `npm i postcss-less` and re-ran `zsh: stylelint "src/**/*.scss"`

Resulting in the following:
```
Error: Cannot find module 'postcss-scss'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/project/node_modules/stylelint/lib/testUtils/createRuleTester.js:9:20)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

I then ran `npm i postcss-scss` and re-ran `zsh: stylelint "src/**/*.scss"`

Which spit out proper stylelint results (errors and warnings based on my config):

`zsh: stylelint "src/**/*.scss"`

```zsh
src/styles/_article-tile.scss
 80:1  ✖  Unexpected unknown at-rule "@include"   at-rule-no-unknown
 92:1  ✖  Unexpected unknown at-rule "@include"   at-rule-no-unknown

src/styles/_breakpoints.scss
  5:1  ✖  Unexpected unknown at-rule "@mixin"     at-rule-no-unknown
  7:5  ✖  Unexpected unknown at-rule "@content"   at-rule-no-unknown
 11:1  ✖  Unexpected unknown at-rule "@mixin"     at-rule-no-unknown
 13:5  ✖  Unexpected unknown at-rule "@content"   at-rule-no-unknown
 17:1  ✖  Unexpected unknown at-rule "@mixin"     at-rule-no-unknown
 20:5  ✖  Unexpected unknown at-rule "@content"   at-rule-no-unknown

src/styles/_category-list.scss
 2:3  ✖  Unexpected unknown at-rule "@include"   at-rule-no-unknown

src/styles/_header.scss
  39:7  ✖  Unexpected unknown at-rule "@include"   at-rule-no-unknown
  81:3  ✖  Unexpected unknown at-rule "@include"   at-rule-no-unknown
 112:5  ✖  Unexpected unknown at-rule "@include"   at-rule-no-unknown

src/styles/_hero-carousel.scss
 24:5  ✖  Unexpected longhand value '0 0 10px 0' instead of '0 0 10px'   shorthand-property-no-redundant-values

src/styles/_mixins.scss
 1:1  ✖  Unexpected unknown at-rule "@mixin"   at-rule-no-unknown

src/styles/_site-nav.scss
 23:7  ✖  Unexpected unknown at-rule "@include"   at-rule-no-unknown
```

I'm wondering if this is a dependency issue within stylelint, or perhaps one of the plugins I'm using, or something wrong with my setup?  Either way, I seem to have fixed it by adding the 'missing' packages, I just don't want them to be direct dependencies of my project since I don't need them.

**Comment by hudochenkov** [comment]
The best way of using stylelint is have it installed as devDependency of your project. I would suggest you to install it that way. You won't have problem with missing dependencies anymore.

**Comment by ntwb** [comment]
+1'ing @hudochenkov advice here @willdavidow, as you've already given the thumbs up I'm going to close this
