### ISSUE TITLE
Error: Undefined rule font-family-no-missing-generic-family-keyword

### ISSUE THREAD

**Issue by ds-manish** [stylelint/stylelint#3067]
**Command**
`$ stylelint --formatter 'verbose' 'public/**/*.css' 'src/**/*.css'`

**Error**
```
Error: Undefined rule font-family-no-missing-generic-family-keyword
    at module.exports (/usr/local/lib/node_modules/stylelint/lib/utils/configurationError.js:8:28)
    at Object.keys.forEach.ruleName (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:302:13)
    at Array.forEach (native)
    at normalizeAllRuleSettings (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:297:29)
    at augmentConfigBasic.then.then.then.augmentedConfig (/usr/local/lib/node_modules/stylelint/lib/augmentConfig.js:91:14)
```

**Versions**
- "angular/cli": "^1.5.5",
- "angular/cdk": "5.0.1",
- "angular/compiler-cli": "^5.0.4",
- "stylelint": "^8.3.1",
- "stylelint-config-standard": "^18.0.0",

**Comment by evilebottnawi** [comment]
@ds-manish you have `stylelint` as global package maybe you have difference version, one version is global second in package.json

**Comment by ds-manish** [comment]
@evilebottnawi 
seems i have different global version then the project version of stylelint.
Thanks.

**Comment by yinsang** [comment]
`npm add --save-dev stylelint`
