### ISSUE TITLE
Fix thrown error for @import statement in <style lang="less"> tag within Vue file

### ISSUE THREAD

**Issue by Xotic750** [stylelint/stylelint#3183]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

My guess is that this is a bug. When I run stylelint from the command line (npm script) it throws a TypeError.

> Which rule, if any, is this issue related to?

Unknown

> What CSS is needed to reproduce this issue?

There are many files and I don't know which one causes the issue. The contents of the log are:
```
Grahams-MacBook-Pro:Byxelkrok grahamfairweather$ cat /Users/grahamfairweather/.npm/_logs/2018-02-20T20_52_23_671Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/Users/grahamfairweather/.nvm/versions/node/v8.9.1/bin/node',
1 verbose cli   '/Users/grahamfairweather/.nvm/versions/node/v8.9.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'lint:css' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'prelint:css', 'lint:css', 'postlint:css' ]
5 info lifecycle prn-calendar@0.0.2~prelint:css: prn-calendar@0.0.2
6 info lifecycle prn-calendar@0.0.2~lint:css: prn-calendar@0.0.2
7 verbose lifecycle prn-calendar@0.0.2~lint:css: unsafe-perm in lifecycle true
8 verbose lifecycle prn-calendar@0.0.2~lint:css: PATH: /Users/grahamfairweather/.nvm/versions/node/v8.9.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/.bin:/usr/local/opt/openssl/bin:/usr/local/opt/openssl/bin:/usr/local/opt/openssl/bin:/usr/local/opt/openssl/bin:/Users/grahamfairweather/.nvm/versions/node/v8.9.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mysql/bin:/usr/local/mysql/bin:/usr/local/mysql/bin:/usr/local/mysql/bin
9 verbose lifecycle prn-calendar@0.0.2~lint:css: CWD: /Users/grahamfairweather/ProReNataJournal/Byxelkrok
10 silly lifecycle prn-calendar@0.0.2~lint:css: Args: [ '-c', 'stylelint \'**/*.{css,sass,scss,less,vue}\'' ]
11 silly lifecycle prn-calendar@0.0.2~lint:css: Returned: code: 1  signal: null
12 info lifecycle prn-calendar@0.0.2~lint:css: Failed to exec lint:css script
13 verbose stack Error: prn-calendar@0.0.2 lint:css: `stylelint '**/*.{css,sass,scss,less,vue}'`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/grahamfairweather/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/grahamfairweather/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid prn-calendar@0.0.2
15 verbose cwd /Users/grahamfairweather/ProReNataJournal/Byxelkrok
16 verbose Darwin 17.2.0
17 verbose argv "/Users/grahamfairweather/.nvm/versions/node/v8.9.1/bin/node" "/Users/grahamfairweather/.nvm/versions/node/v8.9.1/bin/npm" "run" "lint:css"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error prn-calendar@0.0.2 lint:css: `stylelint '**/*.{css,sass,scss,less,vue}'`
22 error Exit status 1
23 error Failed at the prn-calendar@0.0.2 lint:css script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
Grahams-MacBook-Pro:Byxelkrok grahamfairweather$
```
> What stylelint configuration is needed to reproduce this issue?

```
/**
 * @file Manages the root configuration settings for project wide stylelint.
 * @copyright Copyright (c) 2017-present, ProReNata AB
 * @module stylelint/root/configuration
 * @version 1.0.0
 * @since 0.0.2
 * @see {@link https://stylelint.io/} for further information.
 */

module.exports = {
  /**
   * The standard shareable config for stylelint.
   * @type {string|array.<string>}
   * @see {@link https://github.com/stylelint/stylelint-config-standard|standard}
   */
  extends: 'stylelint-config-standard',

  /**
   * @type {array}
   */
  plugins: [],

  /**
   * @type {array}
   */
  processors: [],

  /**
   * @type {!Object}
   */
  rules: {
    // 'no-empty-source': null,
  },
};
```

> Which version of stylelint are you using?

```
    "style-loader": "^0.20.2",
    "stylelint": "^9.0.0",
    "stylelint-config-standard": "^18.1.0",
    "stylelint-webpack-plugin": "^0.10.2",
```
> How are you running stylelint: CLI, PostCSS plugin, Node API?

`"lint:css": "stylelint '**/*.{css,sass,scss,less,vue}'",`

`Grahams-MacBook-Pro:Byxelkrok grahamfairweather$ npm run lint:css`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

We are using LESS

> What did you expect to happen?

To get a report and not throw a TypeError.

> What actually happened (e.g. what warnings or errors you are getting)?

```
Grahams-MacBook-Pro:Byxelkrok grahamfairweather$ npm run lint:css

> prn-calendar@0.0.2 lint:css /Users/grahamfairweather/ProReNataJournal/Byxelkrok
> stylelint '**/*.{css,sass,scss,less,vue}'

TypeError: this[node.type] is not a function
    at Stringifier.stringify (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/postcss/lib/stringifier.js:33:24)
    at Stringifier.body (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/postcss/lib/stringifier.js:96:18)
    at Stringifier.root (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/postcss/lib/stringifier.js:37:14)
    at Stringifier.stringify (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/postcss/lib/stringifier.js:33:24)
    at Stringifier.body (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/postcss/lib/stringifier.js:96:18)
    at Stringifier.root (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/postcss/lib/stringifier.js:37:14)
    at Stringifier.stringify (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/postcss/lib/stringifier.js:33:24)
    at stringify (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/postcss/lib/stringify.js:14:9)
    at Root.toString (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/postcss/lib/node.js:195:9)
    at /Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/stylelint/lib/rules/max-empty-lines/index.js:40:29
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! prn-calendar@0.0.2 lint:css: `stylelint '**/*.{css,sass,scss,less,vue}'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the prn-calendar@0.0.2 lint:css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/grahamfairweather/.npm/_logs/2018-02-20T20_52_23_671Z-debug.log
```

**Comment by hudochenkov** [comment]
Thanks for the report and for using the template.

We need your help to find a solution. Unfortunately it's impossible to find a root of the problem, without know what stylesheet file cause it. Could you find what stylesheet file cause a problem, please? We need file name with (actually only extension of a file matters), and content wich will reproduce an error.

From a log I see that stylelint might not understand syntax correctly. Because, as you said, it's a LESS file, but PostCSS tries to stringify it as regular CSS. Looks like file contains some LESS specific syntax, and stylelint at some point understands it wrong.

**Comment by evilebottnawi** [comment]
@hudochenkov seems in `max-empty-lines` we try to stringify `vue` and it is throw error

**Comment by Xotic750** [comment]
Is there some way that I can get stylelint to tell me which file it throws on, I have nearly 100 files to be processed by the file pattern and currently no idea which one(s) are causing the problem?

**Comment by Xotic750** [comment]
After some further investigation, this seems to be the minimum requirement to cause the problem in a `.vue` file.
```
<template>
</template>

<script>
</script>

<style lang="less">
@import '~CSS/variables.less';
</style>
```
So it seems the import causes the throw. I thought perhaps the alias `~` was the problem, so tried it relative instead.
```
<template>
</template>

<script>
</script>

<style lang="less">
@import '../CSS/variables.less';
</style>
```
But this throws too,

**Comment by CAYdenberg** [comment]
My hunch is that the bug lies in postcss-html, but that's just a guess. Any insight @gucong3000 ?

Thanks @Xotic750 for your sleuthing, I'll try and dig in a bit more tomorrow ...

**Comment by Xotic750** [comment]
I put a `console.log` in the `max-empty-lines/index.js` just before `const rootString = root.toString();` and `JSON.stringified` the variable `root` for a test vue file with the minimum content that I gave above. Here is the result.

```
{
  "raws": {
    "afterEnd": "</style>\n"
  },
  "type": "root",
  "nodes": [
    {
      "raws": {
        "semicolon": false,
        "after": "\n",
        "beforeStart": "<template>\n</template>\n\n<script>\n</script>\n\n<style lang=\"less\">\n"
      },
      "type": "root",
      "nodes": [
        {
          "raws": {
            "before": "  ",
            "afterName": " ",
            "semicolon": true
          },
          "type": "import",
          "nodes": [],
          "name": "import",
          "source": {
            "start": {
              "line": 8,
              "column": 3
            },
            "input": {
              "css": "  @import '~CSS/variables.less';\n",
              "file": "/Users/grahamfairweather/ProReNataJournal/Byxelkrok/test.vue"
            },
            "end": {
              "line": 8,
              "column": 32
            }
          },
          "importPath": "'~CSS/variables.less'",
          "directives": "",
          "lastEach": 50,
          "indexes": {}
        }
      ],
      "source": {
        "input": {
          "css": "  @import '~CSS/variables.less';\n",
          "file": "/Users/grahamfairweather/ProReNataJournal/Byxelkrok/test.vue"
        },
        "start": {
          "line": 8,
          "column": 1
        },
        "isHTMLAttribute": false,
        "isMarkdown": false,
        "isHTMLTag": true,
        "lang": "less",
        "syntax": {},
        "baseIndentLevel": 1
      },
      "lastEach": 50,
      "indexes": {}
    }
  ],
  "source": {
    "input": {
      "css": "<template>\n</template>\n\n<script>\n</script>\n\n<style lang=\"less\">\n  @import '~CSS/variables.less';\n</style>\n",
      "file": "/Users/grahamfairweather/ProReNataJournal/Byxelkrok/test.vue"
    },
    "start": {
      "line": 1,
      "column": 1
    }
  }
}
```

**Comment by Xotic750** [comment]
And this this the stringified `result` variable at the same location.
```
{
  "processor": {
    "version": "6.0.19",
    "plugins": []
  },
  "messages": [],
  "root": {
    "raws": {
      "afterEnd": "</style>\n"
    },
    "type": "root",
    "nodes": [
      {
        "raws": {
          "semicolon": false,
          "after": "\n",
          "beforeStart": "<template>\n</template>\n\n<script>\n</script>\n\n<style lang=\"less\">\n"
        },
        "type": "root",
        "nodes": [
          {
            "raws": {
              "before": "  ",
              "afterName": " ",
              "semicolon": true
            },
            "type": "import",
            "nodes": [],
            "name": "import",
            "source": {
              "start": {
                "line": 8,
                "column": 3
              },
              "input": {
                "css": "  @import '~CSS/variables.less';\n",
                "file": "/Users/grahamfairweather/ProReNataJournal/Byxelkrok/test.vue"
              },
              "end": {
                "line": 8,
                "column": 32
              }
            },
            "importPath": "'~CSS/variables.less'",
            "directives": "",
            "lastEach": 50,
            "indexes": {}
          }
        ],
        "source": {
          "input": {
            "css": "  @import '~CSS/variables.less';\n",
            "file": "/Users/grahamfairweather/ProReNataJournal/Byxelkrok/test.vue"
          },
          "start": {
            "line": 8,
            "column": 1
          },
          "isHTMLAttribute": false,
          "isMarkdown": false,
          "isHTMLTag": true,
          "lang": "less",
          "syntax": {},
          "baseIndentLevel": 1
        },
        "lastEach": 50,
        "indexes": {}
      }
    ],
    "source": {
      "input": {
        "css": "<template>\n</template>\n\n<script>\n</script>\n\n<style lang=\"less\">\n  @import '~CSS/variables.less';\n</style>\n",
        "file": "/Users/grahamfairweather/ProReNataJournal/Byxelkrok/test.vue"
      },
      "start": {
        "line": 1,
        "column": 1
      }
    }
  },
  "opts": {
    "from": "/Users/grahamfairweather/ProReNataJournal/Byxelkrok/test.vue",
    "syntax": {
      "config": {
        "css": {},
        "less": {},
        "sass": {},
        "scss": {},
        "sss": {},
        "sugarss": {}
      }
    }
  },
  "css": "<template>\n</template>\n\n<script>\n</script>\n\n<style lang=\"less\">\n  @import '~CSS/variables.less';\n</style>\n",
  "stylelint": {
    "ruleSeverities": {
      "at-rule-empty-line-before": "error",
      "at-rule-name-case": "error",
      "at-rule-name-space-after": "error",
      "at-rule-semicolon-newline-after": "error",
      "block-closing-brace-empty-line-before": "error",
      "block-closing-brace-newline-after": "error",
      "block-closing-brace-newline-before": "error",
      "block-closing-brace-space-before": "error",
      "block-opening-brace-newline-after": "error",
      "block-opening-brace-space-after": "error",
      "block-opening-brace-space-before": "error",
      "color-hex-case": "error",
      "color-hex-length": "error",
      "comment-empty-line-before": "error",
      "comment-whitespace-inside": "error",
      "custom-property-empty-line-before": "error",
      "declaration-bang-space-after": "error",
      "declaration-bang-space-before": "error",
      "declaration-block-semicolon-newline-after": "error",
      "declaration-block-semicolon-space-after": "error",
      "declaration-block-semicolon-space-before": "error",
      "declaration-block-single-line-max-declarations": "error",
      "declaration-block-trailing-semicolon": "error",
      "declaration-colon-newline-after": "error",
      "declaration-colon-space-after": "error",
      "declaration-colon-space-before": "error",
      "declaration-empty-line-before": "error",
      "function-comma-newline-after": "error",
      "function-comma-space-after": "error",
      "function-comma-space-before": "error",
      "function-max-empty-lines": "error",
      "function-name-case": "error",
      "function-parentheses-newline-inside": "error",
      "function-parentheses-space-inside": "error",
      "function-whitespace-after": "error",
      "indentation": "error",
      "length-zero-no-unit": "error",
      "max-empty-lines": "error",
      "media-feature-colon-space-after": "error",
      "media-feature-colon-space-before": "error",
      "media-feature-name-case": "error",
      "media-feature-parentheses-space-inside": "error",
      "media-feature-range-operator-space-after": "error",
      "media-feature-range-operator-space-before": "error",
      "media-query-list-comma-newline-after": "error",
      "media-query-list-comma-space-after": "error",
      "media-query-list-comma-space-before": "error",
      "no-eol-whitespace": "error",
      "no-missing-end-of-source-newline": "error",
      "number-leading-zero": "error",
      "number-no-trailing-zeros": "error",
      "property-case": "error",
      "rule-empty-line-before": "error",
      "selector-attribute-brackets-space-inside": "error",
      "selector-attribute-operator-space-after": "error",
      "selector-attribute-operator-space-before": "error",
      "selector-combinator-space-after": "error",
      "selector-combinator-space-before": "error",
      "selector-descendant-combinator-no-non-space": "error",
      "selector-list-comma-newline-after": "error",
      "selector-list-comma-space-before": "error",
      "selector-max-empty-lines": "error",
      "selector-pseudo-class-case": "error",
      "selector-pseudo-class-parentheses-space-inside": "error",
      "selector-pseudo-element-case": "error",
      "selector-pseudo-element-colon-notation": "error",
      "selector-type-case": "error",
      "unit-case": "error",
      "value-list-comma-newline-after": "error",
      "value-list-comma-space-after": "error",
      "value-list-comma-space-before": "error",
      "value-list-max-empty-lines": "error",
      "at-rule-no-unknown": "error",
      "block-no-empty": "error",
      "color-no-invalid-hex": "error",
      "comment-no-empty": "error",
      "declaration-block-no-duplicate-properties": "error",
      "declaration-block-no-shorthand-property-overrides": "error",
      "font-family-no-duplicate-names": "error",
      "font-family-no-missing-generic-family-keyword": "error",
      "function-calc-no-unspaced-operator": "error",
      "function-linear-gradient-no-nonstandard-direction": "error",
      "keyframe-declaration-no-important": "error",
      "media-feature-name-no-unknown": "error",
      "no-descending-specificity": "error",
      "no-duplicate-at-import-rules": "error",
      "no-duplicate-selectors": "error",
      "no-empty-source": "error",
      "no-extra-semicolons": "error",
      "no-invalid-double-slash-comments": "error",
      "property-no-unknown": "error",
      "selector-pseudo-class-no-unknown": "error",
      "selector-pseudo-element-no-unknown": "error",
      "selector-type-no-unknown": "error",
      "string-no-newline": "error",
      "unit-no-unknown": "error"
    },
    "customMessages": {},
    "disabledRanges": {
      "all": []
    }
  }
}
```

**Comment by Xotic750** [comment]
After this `const rootString = root.toString();` executes and then we get the TypeError as shown in the original post.
```
TypeError: this[node.type] is not a function
    at Stringifier.stringify (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/postcss/lib/stringifier.js:33:24)
    at Stringifier.body (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/postcss/lib/stringifier.js:96:18)
    at Stringifier.root (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/postcss/lib/stringifier.js:37:14)
    at Stringifier.stringify (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/postcss/lib/stringifier.js:33:24)
    at Stringifier.body (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/postcss/lib/stringifier.js:96:18)
    at Stringifier.root (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/postcss/lib/stringifier.js:37:14)
    at Stringifier.stringify (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/postcss/lib/stringifier.js:33:24)
    at stringify (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/postcss/lib/stringify.js:14:9)
    at Root.toString (/Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/postcss/lib/node.js:195:9)
    at /Users/grahamfairweather/ProReNataJournal/Byxelkrok/node_modules/stylelint/lib/rules/max-empty-lines/index.js:40:29
```

**Comment by Xotic750** [comment]
Looking in the `postcss` `stringify.es` 

https://github.com/postcss/postcss/blob/master/lib/stringifier.es6

the `class` does not have a function for type `import`

**Comment by Xotic750** [comment]
I continued my search and found https://github.com/vuejs/vue-loader/issues/303#issuecomment-259328193

I installed 
`npm install --save-dev stylelint-processor-html`
and now my config looks like this
```
/**
 * @file Manages the root configuration settings for project wide stylelint.
 * @copyright Copyright (c) 2017-present, ProReNata AB
 * @module stylelint/root/configuration
 * @version 1.0.0
 * @since 0.0.2
 * @see {@link https://stylelint.io/} for further information.
 */

module.exports = {
  /**
   * The standard shareable config for stylelint.
   * @type {string|array.<string>}
   * @see {@link https://github.com/stylelint/stylelint-config-standard|standard}
   */
  extends: 'stylelint-config-standard',

  /**
   * @type {array}
   */
  plugins: [],

  /**
   * @type {array}
   */
  processors: ['stylelint-processor-html'],

  /**
   * @type {!Object}
   */
  rules: {
    // 'no-empty-source': null,
  },
};
```
I ran our `npm run lint:css` and it no longer throws an error and now I get a report. But this project is archived and I honestly don't know if I should be using it?

**Comment by gucong3000** [comment]
@Xotic750 Thanks for your sleuthing, it helps me a lot.

@CAYdenberg
I think any less file that contains `@import` can trigger this bug.

**Comment by Xotic750** [comment]
I haven't re-tested our postcss config yet as I have to get that back into the master of our project- However the fix has made it into stylelint and that is now working in our project, so all looking good so far. Thanks!
