### ISSUE TITLE
TypeError: Cannot read property 'addQmark' of undefined

### ISSUE THREAD

**Issue by adambowles** [stylelint/stylelint#3425]
FYI issue, upstream dependency is having an issue which is causing new installs of stylelint to fail.

Posting here for people to find the root cause easier:

https://github.com/micromatch/nanomatch/issues/15

**Comment by evilebottnawi** [comment]
@adambowles can you provide full error stach?

**Comment by adambowles** [comment]
```
$ npm run lint:styles

> my-project@0.1.0 lint:styles /Users/adambowles/Projects/my-project
> stylelint "src/**/style.scss"

TypeError: Cannot read property 'addQmark' of undefined
    at Compiler.<anonymous> (/Users/adambowles/Projects/my-project/node_modules/nanomatch/lib/compilers.js:92:16)
    at Compiler.visit (/Users/adambowles/Projects/my-project/node_modules/snapdragon/lib/compiler.js:129:15)
    at Compiler.mapVisit (/Users/adambowles/Projects/my-project/node_modules/snapdragon/lib/compiler.js:143:12)
    at Compiler.compile (/Users/adambowles/Projects/my-project/node_modules/snapdragon/lib/compiler.js:168:10)
    at Snapdragon.compile (/Users/adambowles/Projects/my-project/node_modules/snapdragon/index.js:156:32)
    at /Users/adambowles/Projects/my-project/node_modules/fast-glob/node_modules/micromatch/index.js:786:23
    at memoize (/Users/adambowles/Projects/my-project/node_modules/fast-glob/node_modules/micromatch/index.js:859:13)
    at Function.micromatch.compile (/Users/adambowles/Projects/my-project/node_modules/fast-glob/node_modules/micromatch/index.js:783:10)
    at create (/Users/adambowles/Projects/my-project/node_modules/fast-glob/node_modules/micromatch/index.js:686:25)
    at /Users/adambowles/Projects/my-project/node_modules/fast-glob/node_modules/micromatch/index.js:695:16
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@0.1.0 lint:styles: `stylelint "src/**/style.scss"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-project@0.1.0 lint:styles script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/adambowles/.npm/_logs/2018-06-27T10_35_27_613Z-debug.log
```

**Comment by evilebottnawi** [comment]
@adambowles can you put also content of `style.scss`?

**Comment by adambowles** [comment]
Error occurs for all files, including zero length files.

**Comment by evilebottnawi** [comment]
@adambowles can you create minimum reproducible test repo?

**Comment by adambowles** [comment]
https://github.com/adambowles/stylelint-3425
