### ISSUE TITLE
npm ERR! 407 Proxy Authentication Required: stylelint@latest

### ISSUE THREAD

**Issue by panchalkalpesh** [stylelint/stylelint#3510]
> Clearly describe the bug

**Getting following error while trying to install stylelint:**
```
npm ERR! code E407
```

> What is needed to reproduce the bug?

```
npm install --global stylelint
```

> Which version of stylelint are you using?

`N/A`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

"CLI with `stylelint "styles/*.scss" --syntax scss --config myconfig.json`"

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

"No"

> What did you expect to happen?

"No errors while installing the package."

> What actually happened (e.g. what warnings or errors did you get)?

 "The following error occurred: `npm-debug.log`"

```shell
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Kalpesh\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'stylelint',
1 verbose cli   '-g' ]
2 info using npm@6.1.0
3 info using node@v8.11.1
4 verbose npm-session de52746574683bec
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 407 https://registry.npmjs.org/stylelint 47ms
8 silly fetchPackageMetaData error for stylelint@latest 407 Proxy Authentication Required: stylelint@latest
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 394ms
11 verbose stack Error: 407 Proxy Authentication Required: stylelint@latest
11 verbose stack     at fetch.then.res (C:\Users\Kalpesh\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
11 verbose stack     at tryCatcher (C:\Users\Kalpesh\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\Kalpesh\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
11 verbose stack     at Promise._settlePromise (C:\Users\Kalpesh\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (C:\Users\Kalpesh\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
11 verbose stack     at Promise._settlePromises (C:\Users\Kalpesh\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
11 verbose stack     at Async._drainQueue (C:\Users\Kalpesh\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
11 verbose stack     at Async._drainQueues (C:\Users\Kalpesh\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues (C:\Users\Kalpesh\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
11 verbose stack     at runCallback (timers.js:794:20)
11 verbose stack     at tryOnImmediate (timers.js:752:5)
11 verbose stack     at processImmediate [as _immediateCallback] (timers.js:729:5)
12 verbose cwd C:\Users\Kalpesh\work\starter-project
13 verbose Windows_NT 10.0.14393
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Kalpesh\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "stylelint" "-g"
15 verbose node v8.11.1
16 verbose npm  v6.1.0
17 error code E407
18 error 407 Proxy Authentication Required: stylelint@latest
19 verbose exit [ 1, true ]
```

**Comment by Arcanemagus** [comment]
This looks to be an error with your NPM proxy configuration, is there a reason you feel it is a bug with stylelint?

**Comment by panchalkalpesh** [comment]
Thanks for your quick response!

I tried the following command and it worked without any errors: 
```
npm i -g npm
```

output: 
```shell
C:\Users\Kalpesh\AppData\Roaming\npm\npm -> C:\Users\Kalpesh\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
C:\Users\Kalpesh\AppData\Roaming\npm\npx -> C:\Users\Kalpesh\AppData\Roaming\npm\node_modules\npm\bin\npx-cli.js
+ npm@6.1.0
updated 1 package in 48.349s
```

**Comment by Arcanemagus** [comment]
```
http fetch GET 407 https://registry.npmjs.org/stylelint 47ms
```

You got a [407 response](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/407) from the request to https://registry.npmjs.org/stylelint, that's entirely on NPM's side.

**Comment by panchalkalpesh** [comment]
You're right, npm had an issue logged ([#14421](https://github.com/npm/npm/issues/14421))

I scanned through the comments and found [this](https://github.com/npm/npm/issues/17396#issuecomment-334123228) solution to have worked for me:
```shell
npm cache verify
npm install --global stylelint
```

output: 
```shell
C:\Users\Kalpesh\AppData\Roaming\npm\stylelint -> C:\Users\Kalpesh\AppData\Roaming\npm\node_modules\stylelint\bin\stylelint.js
+ stylelint@9.4.0
updated 1 package in 31.154s
```
