### ISSUE TITLE
Error on empty comment with comment-empty-line-before

### ISSUE THREAD

**Issue by ypconstante** [stylelint/stylelint#3656]
> Clearly describe the bug

An exception is happening when running running rule `comment-empty-line-before` in an empty comment

> Which rule, if any, is the bug related to?

`comment-empty-line-before`

> What CSS is needed to reproduce the bug?

```scss
// Bootstrap and its default variables
// @import "custom";

//
// //blocks
// @import "blocks/footer";
```

> What stylelint configuration is needed to reproduce the bug?

```
module.exports = {
    extends: ['stylelint-config-standard', 'stylelint-config-recommended-scss'],
    rules: {
        linebreaks: 'unix',
    },
};
```

> Which version of stylelint are you using?

`9.5.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint "src/**/*.scss" --fix`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

Maybe, only tested with SCSS

> What did you expect to happen?

No exception to be thrown

> What actually happened (e.g. what warnings or errors did you get)?

Exception thrown

```shell
TypeError: Cannot read property 'indexOf' of undefined
    at /home/user/project/src/sass/theme/_theme.scss:4:1
    at root.walkComments.comment (/home/user/project/node_modules/stylelint/lib/rules/comment-empty-line-before/index.js:54:22)
    at /home/user/project/node_modules/postcss-scss/node_modules/postcss/lib/container.js:341:16
    at /home/user/project/node_modules/postcss-scss/node_modules/postcss/lib/container.js:146:18
    at Root.each (/home/user/project/node_modules/postcss-scss/node_modules/postcss/lib/container.js:110:16)
    at Root.walk (/home/user/project/node_modules/postcss-scss/node_modules/postcss/lib/container.js:143:17)
    at Root.walkComments (/home/user/project/node_modules/postcss-scss/node_modules/postcss/lib/container.js:339:17)
    at /home/user/project/node_modules/stylelint/lib/rules/comment-empty-line-before/index.js:46:10
    at Promise.resolve.then (/home/user/project/node_modules/stylelint/lib/lintSource.js:221:9)
    at <anonymous>
```

**Comment by ypconstante** [comment]
The problem seems to be with the `linebreaks` config, I'm having other errors with it

```
.label__required { color: #c00000;}
```

```
TypeError: Cannot read property 'search' of undefined
    at /home/user/project/src/sass/theme/_helpers.scss:14:1
    at complain (/home/user/project/node_modules/stylelint/lib/rules/block-closing-brace-newline-before/index.js:79:63)
    at check (/home/user/project/node_modules/stylelint/lib/rules/block-closing-brace-newline-before/index.js:64:11)
    at /home/user/project/node_modules/postcss-scss/node_modules/postcss/lib/container.js:247:18
    at /home/user/project/node_modules/postcss-scss/node_modules/postcss/lib/container.js:146:18
    at Root.each (/home/user/project/node_modules/postcss-scss/node_modules/postcss/lib/container.js:110:16)
    at Root.walk (/home/user/project/node_modules/postcss-scss/node_modules/postcss/lib/container.js:143:17)
    at Root.walkRules (/home/user/project/node_modules/postcss-scss/node_modules/postcss/lib/container.js:245:19)
    at /home/user/project/node_modules/stylelint/lib/rules/block-closing-brace-newline-before/index.js:32:10
    at Promise.resolve.then (/home/ypconstante/Projects/pet-frontend/node_modules/stylelint/lib/lintSource.js:221:9)

```
---

```
&__classe { display: block;width: 100%;}
```

```
TypeError: Cannot read property 'search' of undefined
    at /home/user/project/src/sass/theme/blocks/_consulta.scss:117:25
    at Object.err (/home/user/project/node_modules/stylelint/lib/rules/declaration-block-semicolon-newline-after/index.js:58:53)
    at expectAfter (/home/user/project/node_modules/stylelint/lib/utils/whitespaceChecker.js:306:16)
    at after (/home/user/project/node_modules/stylelint/lib/utils/whitespaceChecker.js:172:9)
    at Object.afterOneOnly (/home/user/project/node_modules/stylelint/lib/utils/whitespaceChecker.js:266:5)
    at root.walkDecls.decl (/home/user/project/node_modules/stylelint/lib/rules/declaration-block-semicolon-newline-after/index.js:51:15)
    at /home/user/project/node_modules/postcss-scss/node_modules/postcss/lib/container.js:198:18
    at /home/user/project/node_modules/postcss-scss/node_modules/postcss/lib/container.js:146:18
    at Rule.each (/home/user/project/node_modules/postcss-scss/node_modules/postcss/lib/container.js:110:16)
    at Rule.walk (/home/user/project/node_modules/postcss-scss/node_modules/postcss/lib/container.js:143:17)
    at /home/user/project/node_modules/postcss-scss/node_modules/postcss/lib/container.js:156:24

```

**Comment by ypconstante** [comment]
Also, the exceptions happen only when running with autofix, when just linting no exception show up.

**Comment by ota-meshi** [comment]
I think the same issue as #3635.
Since [PR](#3636) has been merged, it will be fixed in the next release.
