### ISSUE TITLE
declaration-block-semicolon-newline-before: unable to handle declarations on root

### ISSUE THREAD

**Issue by mahtd** [stylelint/stylelint#397]
In Sass or other extensions that allow variables, declarations are allowed on the root. Stylelint errors when it encounters these though. `declaration-block-semicolon-newline-before` throws this error, but other plugins might be affected since it's coming from a shared utility

added to `warningFreeBasics`:

```js
tr.ok("foo: bar;", "declarations on root")
```

Error:

```
TypeError: Cannot read property 'length' of undefined
    at exports.default (/Users/mattduckman/Developer/stylelint/src/utils/cssStatementBlockString.js:16:81)
    at /Users/mattduckman/Developer/stylelint/src/rules/declaration-block-semicolon-newline-before/index.js:39:23
    at /Users/mattduckman/Developer/stylelint/node_modules/postcss/lib/container.js:88:34
    at /Users/mattduckman/Developer/stylelint/node_modules/postcss/lib/container.js:73:26
    at Root.each (/Users/mattduckman/Developer/stylelint/node_modules/postcss/lib/container.js:59:22)
    at Root.walk (/Users/mattduckman/Developer/stylelint/node_modules/postcss/lib/container.js:72:21)
    at Root.walkDecls (/Users/mattduckman/Developer/stylelint/node_modules/postcss/lib/container.js:86:25)
    at /Users/mattduckman/Developer/stylelint/src/rules/declaration-block-semicolon-newline-before/index.js:30:10
    at LazyResult.run (/Users/mattduckman/Developer/stylelint/node_modules/postcss/lib/lazy-result.js:201:20)
    at LazyResult.sync (/Users/mattduckman/Developer/stylelint/node_modules/postcss/lib/lazy-result.js:188:32)
```

**Comment by mahtd** [comment]
I did some investigation and found that these plugins will throw errors when given a declaration on the root:

* declaration-block-semicolon-newline-before
* declaration-block-semicolon-space-before

Also, the commit that caused this issue is 48531b1 in `src/utils/cssStatementStringBeforeBlock.js`

**Comment by davidtheclark** [comment]
Thanks!
