### ISSUE TITLE
`declaration-block-semicolon-newline-after` throwing error with root declaration and rule

### ISSUE THREAD

**Issue by MadLittleMods** [stylelint/stylelint#402]
Using Stylelint v1.1.0

Does this have to do with the [`Add support for declarations directly on root` 8c165f6c](https://github.com/stylelint/stylelint/commit/8c165f6c3b6b0d80461d53d70f79aca0d34088aa)?

```
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at exports.default (/Users/MadLittleMods/Documents/stylelint-test2/node_modules/stylelint/dist/utils/cssStatementBlockString.js:35:117)
    at /Users/MadLittleMods/Documents/stylelint-test2/node_modules/stylelint/dist/rules/declaration-block-semicolon-newline-after/index.js:58:58
    at /Users/MadLittleMods/Documents/stylelint-test2/node_modules/postcss/lib/container.js:88:34
    at /Users/MadLittleMods/Documents/stylelint-test2/node_modules/postcss/lib/container.js:73:26
    at Root.each (/Users/MadLittleMods/Documents/stylelint-test2/node_modules/postcss/lib/container.js:59:22)
    at Root.walk (/Users/MadLittleMods/Documents/stylelint-test2/node_modules/postcss/lib/container.js:72:21)
    at Root.walkDecls (/Users/MadLittleMods/Documents/stylelint-test2/node_modules/postcss/lib/container.js:86:25)
    at /Users/MadLittleMods/Documents/stylelint-test2/node_modules/stylelint/dist/rules/declaration-block-semicolon-newline-after/index.js:37:10
    at /Users/MadLittleMods/Documents/stylelint-test2/node_modules/stylelint/dist/plugin.js:50:69
    at Array.forEach (native)
```

## Setup

```js
let postcss = require('postcss');
let stylelint = require('stylelint');

let processor = postcss([
	stylelint({
		rules: {
			'declaration-block-semicolon-newline-after': [2, 'always'],
		}
	})
]);
```

Both need to be present to throw the error.

```
$foo-var: 10px;

.foo {

}
```

**Comment by MadLittleMods** [comment]
`stylelint` v1.2.0 solves this issue: https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md#120

> Added: support for declarations directly on root (e.g. Sass variable declarations).

I am pretty sure it was the independent declaration support that fixed it.

**Comment by jeddy3** [comment]
Good stuff. I was trying out your test case out on `1.2.0` when you closed this issue :) Glad it working for you now.
