### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by cyw3** [stylelint/stylelint#4130]
when scan a big project
```
RangeError: Invalid string length
    at results.reduce (/data/codedog/data/tools/node-v8.9.1/lib/node_modules/stylelint/lib/formatters/stringFormatter.js:175:15)
    at Array.reduce (<anonymous>)
    at module.exports (/data/codedog/data/tools/node-v8.9.1/lib/node_modules/stylelint/lib/formatters/stringFormatter.js:162:20)
    at prepareReturnValue (/data/codedog/data/tools/node-v8.9.1/lib/node_modules/stylelint/lib/standalone.js:256:15)
    at globby.then.then.stylelintResults (/data/codedog/data/tools/node-v8.9.1/lib/node_modules/stylelint/lib/standalone.js:245:14)
    at <anonymous>
```

**Comment by hudochenkov** [comment]
Thanks for creating this issue but we are closing it as issues need to follow our issue template so that we can clearly understand your particular circumstances.

Please help us to help you by [recreating the issue](https://github.com/stylelint/stylelint/issues/new/choose) using the template.
