### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by cyw3** [stylelint/stylelint#4133]
> Clearly describe the bug

when scan a big project, has 340M
```
node --max-old-space-size=8192 /data/tools/node-v8.9.1/lib/node_modules/stylelint/bin/stylelint.js --allow-empty-input --ignore-disables --config /data/xxx/.stylelintrc.json "**/*.{css, less, scss, sass, sss}"
```
output error:
```
RangeError: Invalid string length
    at results.reduce (/data/tools/node-v8.9.1/lib/node_modules/stylelint/lib/formatters/stringFormatter.js:175:15)
    at Array.reduce (<anonymous>)
    at module.exports (/data/tools/node-v8.9.1/lib/node_modules/stylelint/lib/formatters/stringFormatter.js:162:20)
    at prepareReturnValue (/data/tools/node-v8.9.1/lib/node_modules/stylelint/lib/standalone.js:256:15)
    at globby.then.then.stylelintResults (/data/tools/node-v8.9.1/lib/node_modules/stylelint/lib/standalone.js:245:14)
    at <anonymous>
```

> Which rule, if any, is the bug related to?

No rule related.

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "extends": "@alloyteam/stylelint-config-standard",
  "defaultSeverity": "warning"
}
```

> Which version of stylelint are you using?

9.3.0

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

CLI with `node --max-old-space-size=8192 /data/tools/node-v8.9.1/lib/node_modules/stylelint/bin/stylelint.js --allow-empty-input --ignore-disables --config /data/xxx/.stylelintrc.json "**/*.{css, less, scss, sass, sss}"`

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

No

> What did you expect to happen?

stylelint run successfully.

> What actually happened (e.g. what warnings or errors did you get)?

```shell
RangeError: Invalid string length
    at results.reduce (/data/tools/node-v8.9.1/lib/node_modules/stylelint/lib/formatters/stringFormatter.js:175:15)
    at Array.reduce (<anonymous>)
    at module.exports (/data/tools/node-v8.9.1/lib/node_modules/stylelint/lib/formatters/stringFormatter.js:162:20)
    at prepareReturnValue (/data/tools/node-v8.9.1/lib/node_modules/stylelint/lib/standalone.js:256:15)
    at globby.then.then.stylelintResults (/data/tools/node-v8.9.1/lib/node_modules/stylelint/lib/standalone.js:245:14)
    at <anonymous>
```

**Comment by evilebottnawi** [comment]
Can you provide more information? Configuration, reproducible test repo or other related information, it is hard to find problem without with infromation

**Comment by hudochenkov** [comment]
You might have a lot of violations and Node.js just could handle the size of the output: https://github.com/nodejs/help/issues/1061#issuecomment-356714457. Try to lint fewer files. Does it helps? As soon as you fix violations, it should become better.
