### ISSUE TITLE
report-invalid-scope-disables Cannot read property 'rules' of undefined

### ISSUE THREAD

**Issue by rgant** [stylelint/stylelint#4479]
Error when running stylelint with the flag `report-invalid-scope-disables`.

```
$ stylelint 'src/**/*.scss' --report-invalid-scope-disables --config .stylelintrc.yml
TypeError: Cannot read property 'rules' of undefined
    at module.exports (./node_modules/stylelint/lib/invalidScopeDisables.js:38:47)
    at prepareReturnValue (./node_modules/stylelint/lib/standalone.js:312:39)
    at ./node_modules/stylelint/lib/standalone.js:286:11
$ stylelint --version
12.0.0
$ ls .stylelintrc.yml 
.stylelintrc.yml
```

> What stylelint configuration is needed to reproduce the bug?

```yaml
extends:
  - stylelint-config-standard
```

> Which version of stylelint are you using?

`12.0.0`

**Comment by littleprincewdk** [comment]
i also met，`12.0.0`
`stylelint$config` is undefined

**Comment by evilebottnawi** [comment]
Please create reproducible test repo, thanks

**Comment by littleprincewdk** [comment]
@evilebottnawi 

repo:
package.json
```
{
  "devDependencies": {
    "stylelint": "^12.0.0"
  }
}
```
.stylelintrc.json
```
{
  "rules": {}
}
```
index.css
```
a {
  color: #aaaaaa;
}
```
this is the command
```
npx stylelint --report-invalid-scope-disables index.css
```
