### ISSUE TITLE
Error: Undefined rule function-calc-no-invalid

### ISSUE THREAD

**Issue by lensbart** [stylelint/stylelint#4488]
I use Stylelint together with Prettier to format `.scss` files on save via the VSCode integration. Recently the autofix functionality stopped working, although formatting errors are still shown with a squiggly underline. Inspecting the console output, we find:

```
["ERROR" - 3:39:25 PM] Error formatting document.
Undefined rule function-calc-no-invalid
Error: Undefined rule function-calc-no-invalid
	at module.exports (/Users/bart/Documents/GitHub.nosync/codebase/node_modules/stylelint/lib/utils/configurationError.js:8:28)
	at /Users/bart/Documents/GitHub.nosync/codebase/node_modules/stylelint/lib/augmentConfig.js:304:13
	at Array.forEach (<anonymous>)
	at normalizeAllRuleSettings (/Users/bart/Documents/GitHub.nosync/codebase/node_modules/stylelint/lib/augmentConfig.js:299:29)
	at /Users/bart/Documents/GitHub.nosync/codebase/node_modules/stylelint/lib/augmentConfig.js:89:14
["INFO" - 3:39:25 PM] Formatting completed in 32.975411ms.
```

Not sure where exactly this bug is caused (`prettier-stylelint`, `stylelint-prettier`, etc), but the autofix behaviour can be restored by commenting out `"function-calc-no-invalid": true,` in `node_modules/stylelint-config-recommended/index.js`.

My `stylelint.config.js` looks as follows:

```js
// @flow strict

module.exports = {
	extends: [
		// 'stylelint-config-standard',
		'stylelint-config-idiomatic-order',
		'./node_modules/prettier-stylelint/config.js'
	],
	plugins: ['stylelint-prettier', 'stylelint-scss'],
	rules: {
		'at-rule-no-unknown': null,
		'at-rule-no-vendor-prefix': true, // vendor prefixes handled by autoprefixer
		'color-named': 'always-where-possible',
		'declaration-empty-line-before': [
			'always',
			{
				except: ['after-comment', 'after-declaration', 'first-nested']
			}
		],
		'declaration-no-important': true,
		'declaration-property-value-blacklist': {
			// Use a Sass `$constant` instead of a number, and maintain all z-index
			// constants together in `app/styles/constants` to avoid unexpected overlap
			'z-index': [/\d+/]
		},
		indentation: 'tab',
		'media-feature-name-no-vendor-prefix': true, // vendor prefixes handled by autoprefixer
		'order/properties-alphabetical-order': true,
		'order/properties-order': [],
		'property-no-vendor-prefix': true, // vendor prefixes handled by autoprefixer
		'scss/at-extend-no-missing-placeholder': true,
		'scss/at-import-no-partial-leading-underscore': true,
		'scss/at-import-partial-extension': 'never',
		'scss/at-rule-no-unknown': true,
		'scss/dimension-no-non-numeric-values': true,
		'scss/dollar-variable-empty-line-before': [
			'always',
			{
				disableFix: false,
				except: ['first-nested', 'after-comment', 'after-dollar-variable']
			}
		],
		'scss/double-slash-comment-whitespace-inside': 'always',
		'scss/no-duplicate-dollar-variables': true,
		'scss/no-duplicate-mixins': true,
		'selector-no-vendor-prefix': true, // vendor prefixes handled by autoprefixer
		'selector-pseudo-class-no-unknown': [
			true,
			{ ignorePseudoClasses: ['global'] }
		],
		'unit-whitelist': [
			'deg',
			'dppx',
			// 'em',
			'fr',
			'ms',
			'px',
			'rem',
			's',
			'vh',
			'vw',
			'%'
		],
		'value-no-vendor-prefix': true // vendor prefixes handled by autoprefixer
	}
}
```

Overwriting `'function-calc-no-invalid': false` in `stylelint.config.js` doesn’t work (neither with `undefined`)

All my dependencies are up-to-date.

**Comment by lensbart** [comment]
As it turns out, I have a `stylelint` subdependency via `prettier-stylelint@^0.4.2` which needs to be `^8.1.1` and so happens to be version `8.4.0`. `stylelint` itself is not a direct dependency of my project, but if I add it via `yarn add -D stylelint`, this subdependency is upgraded to the latest version, `12`.

... and now I see the changelog mentioning “Removed: `stylelint` < 10.1.0 from peer dependencies. stylelint@10.1.0+ is required now.”.

💁‍♂️
🤦‍♂️
