### ISSUE TITLE
indentation error

### ISSUE THREAD

**Issue by XhmikosR** [stylelint/stylelint#4563]
I was trying to test the current master with some rules and I hit this by accident:

```
C:\Users\xmr\Desktop\stylelint>npm run benchmark-rule indentation 2

> stylelint@13.0.0 benchmark-rule C:\Users\xmr\Desktop\stylelint
> node scripts/benchmark-rule.js "indentation" "2"

TypeError: Cannot read property 'baseIndentLevel' of null
    at <input css 1>:1:1
    at indentationLevel (C:\Users\xmr\Desktop\stylelint\lib\rules\indentation\index.js:143:64)
    at C:\Users\xmr\Desktop\stylelint\lib\rules\indentation\index.js:54:22
    at C:\Users\xmr\Desktop\stylelint\node_modules\postcss\lib\container.js:135:18
    at Root.each (C:\Users\xmr\Desktop\stylelint\node_modules\postcss\lib\container.js:101:16)
    at Root.walk (C:\Users\xmr\Desktop\stylelint\node_modules\postcss\lib\container.js:131:17)
    at C:\Users\xmr\Desktop\stylelint\lib\rules\indentation\index.js:53:8
    at LazyResult.run (C:\Users\xmr\Desktop\stylelint\node_modules\postcss\lib\lazy-result.js:295:14)
    at LazyResult.asyncTick (C:\Users\xmr\Desktop\stylelint\node_modules\postcss\lib\lazy-result.js:208:26)
    at C:\Users\xmr\Desktop\stylelint\node_modules\postcss\lib\lazy-result.js:250:14
    at new Promise (<anonymous>)
```

If I switch to the v12.0.1 tag, then it works fine. Is this something expected or did it broke accidentally?

**Comment by XhmikosR** [comment]
It seems this broke in #4458 

We need to have a closer look at #4458 @hudochenkov in case something else broke.

**Comment by XhmikosR** [comment]
I can revert the default `options` param for the time being; it's because options is null and thus it doesn't work.

But let's review the aforementioned PR one more time in case there are more cases we pass null or other falsy values.

**Comment by XhmikosR** [comment]
Might be related to #4551.

**Comment by jeddy3** [comment]
> Might be related to #4551 if not the same

I suspect so.

**Comment by jeddy3** [comment]
Closing [as stylistic rules are frozen](https://github.com/stylelint/stylelint/issues/5674). The community is welcome to migrate the rule [to a plugin](https://stylelint.io/developer-guide/plugins) and fix this bug.
