### ISSUE TITLE
Error: Cannot find module 'postcss-html/extract

### ISSUE THREAD

**Issue by ACVis** [stylelint/stylelint#4615]
> Clearly describe the bug

Open a markdown file (empty or with content) and receive an error.

> What code is needed to reproduce the bug?

Just a markdown file.

> What stylelint configuration is needed to reproduce the bug?

Looking at the trace, I don't think it matters, but I can provide my stylelint config if needed.

> Which version of stylelint are you using?

13.2.0

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

VSCode extension: https://github.com/stylelint/vscode-stylelint

> What did you expect to happen?

With the old shinnn VSCode plugin, and version 11.0 of stylelint, I had no errors.

> What actually happened (e.g. what warnings or errors did you get)?

VSCode reports the following error:

```Error: Cannot find module 'postcss-html/extract' Require stack: - 
d:\MyProject\node_modules\postcss-markdown\extract.js - 
d:\MyProject\node_modules\postcss-syntax\processor.js - 
d:\MyProject\node_modules\postcss-syntax\parse.js - 
d:\MyProject\node_modules\postcss-syntax\index.js - 
d:\MyProject\node_modules\stylelint\lib\getPostcssResult.js - 
d:\MyProject\node_modules\stylelint\lib\createStylelint.js - 
d:\MyProject\node_modules\stylelint\lib\index.js - 
c:\Users\username\.vscode\extensions\stylelint.vscode-stylelint-0.83.0\lib\stylelint-vscode\index.js - 
c:\Users\username\.vscode\extensions\stylelint.vscode-stylelint-0.83.0\server.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
at Function.Module._load (internal/modules/cjs/loader.js:531:27)
at Module.require (internal/modules/cjs/loader.js:685:19)
at require (internal/modules/cjs/helpers.js:16:16)
at mdParser (d:\MyProject\node_modules\postcss-markdown\extract.js:9:12)
at processor (d:\MyProject\node_modules\postcss-syntax\processor.js:25:43)
at Object.parse (d:\MyProject\node_modules\postcss-syntax\parse.js:25:10)
at new LazyResult (d:\MyProject\node_modules\postcss\lib\lazy-result.js:60:16)
at d:\MyProject\node_modules\stylelint\lib\getPostcssResult.js:123:19

Source: stylelint (Extension)
```

**Comment by jeddy3** [comment]
> Edit: Might this issue make more sense in the extension's repository?

Yes, I'll transfer the issue as I can't replicate the problem using the CLI.
