### ISSUE TITLE
Fix TypeError for inline comments and autofix in max-empty-lines 

### ISSUE THREAD

**Issue by ecuplxd** [stylelint/stylelint#4820]
> Clearly describe the bug

if had inline comment in a rule, special -s=sugarss --fix make throw TypeError

> Which rule, if any, is the bug related to?

`max-empty-lines`

> What code is needed to reproduce the bug?

```css
a {
  width: 00.1em; // inline comment
}
```

> What stylelint configuration is needed to reproduce the bug?

```json
{
  "rules": {
    "max-empty-lines": 1
  }
}
```

> Which version of stylelint are you using?

13.5.0

> How are you running stylelint: CLI, PostCSS plugin, Node.js API?

"CLI with `stylelint "**/*.sss" --config myconfig.json -s=sugarss --fix`"

> Does the bug relate to non-standard syntax (e.g. SCSS, Less etc.)?

sugarss inline comment

> What did you expect to happen?

no error throw

> What actually happened (e.g. what warnings or errors did you get)?

```shell
TypeError: Cannot read property 'replace' of undefined

    at <input css 189>:1:1
    at replaceEmptyLines (lib/rules/max-empty-lines/index.js:175:18)
    at apply (node_modules/lodash/lodash.js:475:27)
    at getChars (node_modules/lodash/lodash.js:5317:16)
    at callback (lib/rules/max-empty-lines/index.js:60:25)
    at callback (node_modules/postcss/lib/container.es6:110:18)
    at Root.each (node_modules/postcss/lib/container.es6:76:16)
    at Root.walk (node_modules/postcss/lib/container.es6:107:17)
    at lib/rules/max-empty-lines/index.js:51:9
    at lib/lintSource.js:210:6
        at Array.map (<anonymous>)
```

**Comment by jeddy3** [comment]
Fixed in https://github.com/stylelint/stylelint/pull/4821
