### ISSUE TITLE
TypeError: rangeData.all is not iterable needlessDisables.js:61:33

### ISSUE THREAD

**Issue by olderor** [stylelint/stylelint#5092]
> Clearly describe the bug

The issue in version 13.8.0 (13.7.2 was working correctly).

The error:
```
TypeError: rangeData.all is not iterable
    at node_modules\stylelint\lib\needlessDisables.js:61:33
    at Array.forEach (<anonymous>)
    at module.exports (node_modules\stylelint\lib\needlessDisables.js:15:10)
    at prepareReturnValue (node_modules\stylelint\lib\prepareReturnValue.js:30:30)
    at node_modules\stylelint\lib\standalone.js:289:16
error Command failed with exit code 1.
```

Probably some regression introduced in this PR https://github.com/stylelint/stylelint/pull/4973

The version of node I use: 12.18.1

> Which rule, if any, is the bug related to?

No specific rules, the issue seems to be in the core.

> What code is needed to reproduce the bug?

No code is needed, just run stylelint. `npx stylelint \"**/*.scss\" --max-warnings 0 --risd --rdd --rd`

**Comment by hudochenkov** [comment]
Please use issue template. We can't help with these details.

**Comment by olderor** [comment]
Hi @nex3 , can you please take a look at the issue as you were the author of the PR? Thanks.

**Comment by nex3** [comment]
This isn't enough info for me to reproduce. From a visual inspection of the code, it looks like `disabledRanges.all` is always set to an array, so it's unclear *a priori* why this would fail:

https://github.com/stylelint/stylelint/blob/5601902f0d630d8b8f65e842445a678e9d95bebb/lib/assignDisabledRanges.js#L51-L59

If you can provide me with a stylelint config and CSS file that consistently reproduces this, I can dive in further.

**Comment by olderor** [comment]
Closing the issue as I cannot repro it now.

**Comment by olderor** [comment]
FYI: After my investigation, I figured out that the issue was causing 'ignoreFiles' in the configuration. For some reason, the new version of stylelint was producing this error, when the old version was working normally. Once I removed ignoreFiles, and moved the patterns to .stylelintignore instead, the issue was gone. Not sure why ignoreFiles is causing this behavior.

**Comment by starikcetin** [comment]
This problem still exists. As soon as I added `ignoreFiles`, I started getting this error. The problem is the VSCode extension `stylelint.vscode-stylelint` does not respect my `.stylelintignore` file, so I am kind of stuck here.

**Comment by fiso** [comment]
I still have this problem. Here is my config out of a screenshot.
![image](https://user-images.githubusercontent.com/482355/113254224-996a6a00-92c6-11eb-9cf8-c477f3827a70.png)

**Comment by nex3** [comment]
Again, if you can provide me a minimal reproduction of this issue, I can investigate further.

**Comment by olderor** [comment]
From a visual inspection of the code, I've found at least 2 places where disabledRanges is not initialized as you expect:

https://github.com/stylelint/stylelint/blob/a48f2aedab2d56198727d7b9aae2c84e99c25fba/lib/utils/report.js#L39-L42

https://github.com/stylelint/stylelint/blob/0a2e727abf166cc4083da9ecbb99ab39c05c65e2/lib/lintSource.js#L68-L72

**Comment by olderor** [comment]
Reopening as the issue is reported by multiple people, but for me the workaround was to move the patterns to .stylelintignore

**Comment by Mouvedia** [comment]
@olderor would adding
```json
"disabledRanges": { 
  "all": [], 
}
```
lintSource.js and report.js to fix the problem?

If not, would adding [this piece of information](https://github.com/stylelint/stylelint/issues/5092#issuecomment-815500208) to the documentation fix this issue?
