### ISSUE TITLE
Error being thrown when running with --fix option

### ISSUE THREAD

**Issue by nicreichert** [stylelint/stylelint#5096]
When I run stylelint on its own (`yarn stylelint ./src`), it works normally and point me the warnings and errors. However, when I run it with `--fix` option, I see the following error message:

```
TypeError: this.input.fromOffset is not a function
    at TemplateSafeParser.getPosition (project/node_modules/postcss-safe-parser/node_modules/postcss/lib/parser.js:379:26)
    at TemplateSafeParser.init (project/node_modules/postcss-safe-parser/node_modules/postcss/lib/parser.js:391:19)
    at TemplateSafeParser.literal (project/node_modules/@stylelint/postcss-css-in-js/template-parser-helper.js:41:7)
    at TemplateSafeParser.other (project/node_modules/@stylelint/postcss-css-in-js/template-safe-parser.js:15:25)
    at TemplateSafeParser.parse (project/node_modules/postcss-safe-parser/node_modules/postcss/lib/parser.js:59:16)
    at Object.templateSafeParse [as parse] (project/node_modules/@stylelint/postcss-css-in-js/template-safe-parse.js:14:9)
    at LocalFixer.parse (project/node_modules/postcss-syntax/parse-style.js:57:18)
    at parseStyle (project/node_modules/postcss-syntax/parse-style.js:88:39)
    at project/node_modules/postcss-syntax/parse-style.js:103:17
    at Array.forEach (<anonymous>)
```

While trying to debug it, I noticed that the `input` value trying to be accessed on `/postcss-safe-parser/node_modules/postcss/lib/parser.js:379:26` has no `fromOffset` property, hence, the error is thrown. 

I can't correlate this to any specific rule, and it was working normally till couple of days ago. All that I changed in the project was that I upgraded `react-scripts` from v3.x to 4.x, and I'm using it with `styled-components` config.

Here's my config:

```json
{
  "extends": [
    "stylelint-config-recommended",
    "stylelint-config-styled-components"
  ],
  "rules": {
    "property-no-vendor-prefix": null,
    "no-extra-semicolons": null,
    "function-calc-no-invalid": null
  }
}
```

versions
```
    "stylelint": "^13.8.0",
    "stylelint-config-recommended": "^3.0.0",
    "stylelint-config-styled-components": "^0.1.1",
```

Has anyone faced this issue and knows how to properly address this? I already tried clearing `node_modules` and `package-lock.json` and reinstalling everything, but no cigar.

**Comment by hudochenkov** [comment]
Could you provide a repository with minimal reproducible example, please?

**Comment by nicreichert** [comment]
I actually found the issue. Basically, updating `react-scripts` to 4.0.1 created a version conflict for `postcss-safe-parser`.
