### ISSUE TITLE
Error when using gulp-postcss with stylelint processor

### ISSUE THREAD

**Issue by vyorkin** [stylelint/stylelint#523]
the stack trace:

```
/Users/vyorkin/github/starter-kit/node_modules/postcss/lib/lazy-result.js:43
        if (typeof css === 'object' && css.type === 'root') {
                                          ^

TypeError: Cannot read property 'type' of null
    at new LazyResult (/Users/vyorkin/github/starter-kit/node_modules/postcss/lib/lazy-result.js:43:43)
    at Processor.process (/Users/vyorkin/github/starter-kit/node_modules/postcss/lib/processor.js:36:16)
    at Transform.stream._transform (/Users/vyorkin/github/starter-kit/node_modules/gulp-postcss/index.js:44:8)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Transform.Writable.write (_stream_writable.js:207:11)
    at write (/Users/vyorkin/github/starter-kit/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/vyorkin/github/starter-kit/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/vyorkin/github/starter-kit/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at emitReadable_ (/Users/vyorkin/github/starter-kit/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/vyorkin/github/starter-kit/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/vyorkin/github/starter-kit/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
```

and this is my linting gulp task:
```
...
var postcss = require('gulp-postcss');
...

gulp.task('lint:css', () => {
  const processors = [
      stylelint({
        config: '/Users/vyorkin/github/starter-kit/.stylelintrc',
        configBasedir: '/Users/vyorkin/github/starter-kit',
        files: '/Users/vyorkin/github/starter-kit/**/*.css'
    }),
    reporter({ clearMessages: true })
  ];
  return gulp.src('/Users/vyorkin/github/starter-kit/**/*.css').pipe(postcss(processors));
});
```

but it works when I use CLI

**Comment by vyorkin** [comment]
I've just tried to reproduce with minimum config. [Here is the repo that reproduces the issue](https://github.com/vyorkin/gulp-stylelint-minimal-example)

**Comment by vyorkin** [comment]
the stack trace:

```
~/programming/play/stylelint master*
❯ gulp lint
[15:59:26] Using gulpfile ~/programming/play/stylelint/gulpfile.js
[15:59:26] Starting 'lint'...
[15:59:26] 'lint' errored after 28 ms
[15:59:26] Error in plugin 'gulp-postcss'
Message:
    No rules found within configuration
Details:
    code: 78
```

**Comment by TrySound** [comment]
@vyorkin in stylelint2 stylelintrc should be strict json here need to wrap `except` in quote
https://github.com/vyorkin/gulp-stylelint-minimal-example/blob/master/.stylelintrc#L4

**Comment by vyorkin** [comment]
I removed all of the rules, expect just one `"selector-no-id": 2`, pushed

**Comment by davidtheclark** [comment]
The `config` property in your plugin options needs to be an object, not a path. Try changing it to `configFile`: http://stylelint.io/?/docs/user-guide/postcss-plugin.md

**Comment by vyorkin** [comment]
@davidtheclark @TrySound I've changed it to use the `configFile` option instead of just `config` in the [use-the-right-option](https://github.com/vyorkin/gulp-stylelint-minimal-example/tree/use-the-right-option) branch, but now it says:
```
~/programming/play/stylelint master*
❯ gulp lint
[16:53:28] Using gulpfile ~/programming/play/stylelint/gulpfile.js
[16:53:28] Starting 'lint'...
[16:53:28] 'lint' errored after 28 ms
[16:53:28] Error in plugin 'gulp-postcss'
Message:
    configFile path "/Users/vyorkin/programming/play/stylelint/.stylelintrc" corresponded to no file
Details:
    code: 78
```

**Comment by davidtheclark** [comment]
Should that path correspond to a file, or do you have the wrong path? I thought you were trying to look in '/Users/vyorkin/github/starter-kit/.stylelintrc'?

**Comment by vyorkin** [comment]
I've renamed .stylelintrc to stylelint.json in [another branch](https://github.com/vyorkin/gulp-stylelint-minimal-example/tree/json-instead-of-rc) and that way it works

**Comment by vyorkin** [comment]
@davidtheclark Yeah, its the right path, I've copied it and `cat /Users/vyorkin/github/starter-kit/.stylelintrc`:
```
~/programming/play/stylelint use-the-right-option
❯ cat cat /Users/vyorkin/github/starter-kit/.stylelintrc
cat: cat: No such file or directory
{
  "extends": "stylelint-config-suitcss"
  "rules": {
    "block-no-empty": 2,
    "color-no-invalid-hex": 2,
    "declaration-colon-space-after": [2, "always"],
    "declaration-colon-space-before": [2, "never"],
    "function-comma-space-after": [2, "always"],
    "function-url-quotes": [2, "single"],
    "media-feature-colon-space-after": [2, "always"],
    "media-feature-colon-space-before": [2, "never"],
    "media-feature-name-no-vendor-prefix": 2,
    "no-multiple-empty-lines": 2,
    "number-leading-zero": [2, "never"],
    "number-no-trailing-zeros": 2,
    "property-no-vendor-prefix": 2,
    "rule-no-duplicate-properties": 2,
    "rule-no-single-line": 2,
    "rule-trailing-semicolon": [2, "always"],
    "selector-list-comma-newline-after": [2, "always-multi-line"],
    "selector-no-id": 2,
    "string-quotes": [2, "single"],
    "value-no-vendor-prefix": 2
  }
}
```

**Comment by davidtheclark** [comment]
Ok, I think I've found the issue: https://github.com/stylelint/stylelint/blob/master/src/postcssPlugin.js#L68

If you pass a file directly it cannot be an `rc` file: it needs to be a JSON file so that it can be `required()`. This will be improved in v3, but for how that's the situation. We should update the docs.

**Comment by davidtheclark** [comment]
Actually, the docs already stay this:

> configFile
> The path to a JSON or JS file (with a .json or .js extension) that contains your stylelint configuration object.

So we're covered.

**Comment by vyorkin** [comment]
Sorry, I've read just this project's wiki, maybe I've missed smth. Anyway, I'm don't care if its json or rc file.
Thanks for your help and for this great tool!

**Comment by davidtheclark** [comment]
No problem: there's a lot to read there.
