### ISSUE TITLE
TypeError: this.getPosition is not a function in LessParser.inlineComment 

### ISSUE THREAD

**Issue by PlayApple** [stylelint/stylelint#5666]
TypeError: this.getPosition is not a function

"lint:style": "stylelint --fix "src/**/*.less" --custom-syntax postcss-less"

TypeError: this.getPosition is not a function
at LessParser.inlineComment (/web/node_modules/postcss-less/lib/LessParser.js:71:28)
at LessParser.isInlineComment (/web/node_modules/postcss-less/lib/nodes/inline-comment.js:37:12)
at LessParser.other (/web/node_modules/postcss-less/lib/LessParser.js:156:36)
at LessParser.parse (/web/node_modules/postcss/lib/parser.js:75:16)
at parse (/web/node_modules/postcss-less/lib/index.js:11:12)
at new LazyResult (/web/node_modules/stylelint/node_modules/postcss/lib/lazy-result.js:133:16)
at getPostcssResult (/web/node_modules/stylelint/lib/getPostcssResult.js:77:30)
at async lintSource (/web/node_modules/stylelint/lib/lintSource.js:76:4)
at async /web/node_modules/stylelint/lib/standalone.js:218:27
at async Promise.all (index 0)

How can i fixed it. Thanks.

**Comment by zheeeng** [comment]
@lachieh @alexander-akait  I'm using PNPM and encountered the same problem.

```
pnpm ls postcss-less

devDependencies:
postcss-less 5.0.0
```

```
pnpm ls postcss

devDependencies:
postcss 8.3.11
```

**Comment by ybiquitous** [comment]
@NansD Can you provide your `.stylelintrc` file, please? I'm curious where `customSyntax: 'postcss-less'` is.

**Comment by NansD** [comment]
Thank you for your help !

my .stylelintrc.json was like this : 
```
{
  "extends": "stylelint-config-standard",
  "customSyntax": "postcss-less"
}
```

And I just tried transforming it to a js file like so : 
```
module.exports = {
  "extends": "stylelint-config-standard",
  "customSyntax": require("postcss-less")
}
```

but still get `TypeError: this.getPosition is not a function`

**Comment by cong1223** [comment]
> 

if you use less , these deps you have to install :
` "postcss": "8",
    "postcss-less": "^6.0.0",
    "stylelint": "^14.5.1",
    "stylelint-config-recommended-less": "^1.0.4",
`

**Comment by NansD** [comment]
It works, thank you!
