### ISSUE TITLE
Stilelint Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by Unyielding1** [stylelint/stylelint#6030]
### What steps are needed to reproduce the bug?

after I use the stilelint  auto-fix command in visual studio this problem appears

### What Stylelint configuration is needed to reproduce the bug?

 name: Stylelint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Setup Stylelint
        run: |
          npm install --save-dev stylelint@13.x stylelint-scss@3.x stylelint-config-standard@21.x stylelint-csstree-validator@1.x
          [ -f .stylelintrc.json ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/html-css/.stylelintrc.json
      - name: Stylelint Report
        run: npx stylelint "**/*.{css,scss}"

### How did you run Stylelint?

npx stylelint "**/*.css" --fix

### Which version of Stylelint are you using?

13.13.1

### What did you expect to happen?

i expect the 3 limpers give me a green status but only stylelint do that

### What actually happened?

Run npx stylelint "**/*.{css,scss}"
  npx stylelint "**/*.{css,scss}"
  shell: /bin/bash -e {0}
  env:
    FORCE_COLOR: 1
Error: Cannot find module 'postcss/lib/input'
Require stack:
- /home/runner/work/Portfolio-setup-and-mobile-version-skeleton/Portfolio-setup-and-mobile-version-skeleton/node_modules/postcss-syntax/parse-style.js
- /home/runner/work/Portfolio-setup-and-mobile-version-skeleton/Portfolio-setup-and-mobile-version-skeleton/node_modules/postcss-syntax/processor.js
- /home/runner/work/Portfolio-setup-and-mobile-version-skeleton/Portfolio-setup-and-mobile-version-skeleton/node_modules/postcss-syntax/parse.js
- /home/runner/work/Portfolio-setup-and-mobile-version-skeleton/Portfolio-setup-and-mobile-version-skeleton/node_modules/postcss-syntax/index.js
- /home/runner/work/Portfolio-setup-and-mobile-version-skeleton/Portfolio-setup-and-mobile-version-skeleton/node_modules/stylelint/lib/getPostcssResult.js
- /home/runner/work/Portfolio-setup-and-mobile-version-skeleton/Portfolio-setup-and-mobile-version-skeleton/node_modules/stylelint/lib/createStylelint.js
- /home/runner/work/Portfolio-setup-and-mobile-version-skeleton/Portfolio-setup-and-mobile-version-skeleton/node_modules/stylelint/lib/printConfig.js
- /home/runner/work/Portfolio-setup-and-mobile-version-skeleton/Portfolio-setup-and-mobile-version-skeleton/node_modules/stylelint/lib/cli.js
- /home/runner/work/Portfolio-setup-and-mobile-version-skeleton/Portfolio-setup-and-mobile-version-skeleton/node_modules/stylelint/bin/stylelint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:[2](https://github.com/Unyielding1/Portfolio-setup-and-mobile-version-skeleton/runs/6120282226?check_suite_focus=true#step:5:2)7)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/home/runner/work/Portfolio-setup-and-mobile-version-skeleton/Portfolio-setup-and-mobile-version-skeleton/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/runner/work/Portfolio-setup-and-mobile-version-skeleton/Portfolio-setup-and-mobile-version-skeleton/node_modules/postcss-syntax/parse-style.js:[3](https://github.com/Unyielding1/Portfolio-setup-and-mobile-version-skeleton/runs/6120282226?check_suite_focus=true#step:5:3):15)
    at Module._compile (/home/runner/work/Portfolio-setup-and-mobile-version-skeleton/Portfolio-setup-and-mobile-version-skeleton/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:1[4](https://github.com/Unyielding1/Portfolio-setup-and-mobile-version-skeleton/runs/6120282226?check_suite_focus=true#step:5:4))
    at Module.require (internal/modules/cjs/loader.js:88[7](https://github.com/Unyielding1/Portfolio-setup-and-mobile-version-skeleton/runs/6120282226?check_suite_focus=true#step:5:7):1[9](https://github.com/Unyielding1/Portfolio-setup-and-mobile-version-skeleton/runs/6120282226?check_suite_focus=true#step:5:9))
Error: Process completed with exit code 1.

### Does the bug relate to non-standard syntax?

only working in html and Css

**Comment by jeddy3** [comment]
Please upgrade to [Stylelint 14](https://stylelint.io/CHANGELOG#1400).

[Migration Guide](https://stylelint.io/migration-guide/to-14).
