### ISSUE TITLE
Stylelint doesn't seem to work with Vite

### ISSUE THREAD

**Issue by theolavaux** [stylelint/stylelint#6067]
### What steps are needed to reproduce the bug?

1 - Create a new Vite project
2 - Install `stylelint stylelint-config-standard postcss-html`
3 - Create `.stylelint.config.js` with config from below
4 - Run linting

### What Stylelint configuration is needed to reproduce the bug?

```js
module.exports = {
  extends: [
    'stylelint-config-standard',
  ],
};

```

### How did you run Stylelint?

stylelint \"**/*.vue\" --ignore-path .gitignore

### Which version of Stylelint are you using?

`14.8.2`

### What did you expect to happen?

See Stylelint linting

### What actually happened?

```bash

Error: Cannot find module 'util-deprecate'
Require stack:
- /Users/theo/project/node_modules/postcss-selector-parser/dist/selectors/attribute.js
- /Users/theo/project/node_modules/postcss-selector-parser/dist/parser.js
- /Users/theo/project/node_modules/postcss-selector-parser/dist/processor.js
- /Users/theo/project/node_modules/postcss-selector-parser/dist/index.js
- /Users/theo/project/node_modules/stylelint/lib/utils/parseSelector.js
- /Users/theo/project/node_modules/stylelint/lib/rules/selector-attribute-brackets-space-inside/index.js
- /Users/theo/project/node_modules/stylelint/lib/rules/index.js
- /Users/theo/project/node_modules/stylelint/lib/normalizeRuleSettings.js
- /Users/theo/project/node_modules/stylelint/lib/normalizeAllRuleSettings.js
- /Users/theo/project/node_modules/stylelint/lib/augmentConfig.js
- /Users/theo/project/node_modules/stylelint/lib/createStylelint.js
- /Users/theo/project/node_modules/stylelint/lib/resolveConfig.js
- /Users/theo/project/node_modules/stylelint/lib/printConfig.js
- /Users/theo/project/node_modules/stylelint/lib/cli.js
- /Users/theo/project/node_modules/stylelint/bin/stylelint.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/Users/theo/project/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/theo/project/node_modules/postcss-selector-parser/dist/selectors/attribute.js:27:17)
    at Module._compile (/Users/theo/project/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

### Does the bug relate to non-standard syntax?

Yes `.vue`

**Comment by alexander-akait** [comment]
Sorry, but vite is not related to stylelint, please ask this in stackoverflow or vite repo

**Comment by theolavaux** [comment]
The stacktrace pasted above to Stylelint not Vite 🤔

**Comment by ybiquitous** [comment]
@theolavaux If you want to lint Vue files, I recommend using [stylelint-config-recommended-vue](https://www.npmjs.com/package/stylelint-config-recommended-vue). See also our [doc](https://stylelint.io/user-guide/get-started/#using-a-community-shared-config) for community-based configs.

---

`util-deprecate` should be installed with `postcss-selector-parser`, so it's weird to raise `Error: Cannot find module 'util-deprecate'`.

```console
$ npm v postcss-selector-parser dependencies
{ cssesc: '^3.0.0', 'util-deprecate': '^1.0.2' }
```

There may be a problem with dependency installation on your environment, but I cannot know more without more details for reproduction. For now, it doesn't seem a problem for Stylelint itself to me.

**Comment by alexander-akait** [comment]
Can you show `package.json`?

**Comment by theolavaux** [comment]
Also, I'm using Yarn 2 with `nodeLinker: node-modules`, that might explain why some package are missing

_package.json_
```json
{
  "workspaces": [
    "packages/components/**/*"
  ],
  "scripts": {
    "postinstall": "is-ci || husky install",
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "lint:js": "eslint --ext \".ts,.vue\" --ignore-path .gitignore .",
    "fix:js": "eslint --fix --ext \".ts,.vue\" --ignore-path .gitignore .",
    "lint:style": "stylelint \"**/*.{vue,scss}\" --ignore-path .gitignore",
    "fix:style": "stylelint --fix \"**/*.{vue,scss}\" --ignore-path .gitignore",
    "lint": "yarn lint:js && yarn lint:style",
  },
  "dependencies": {
    "vue": "3.2.33"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "5.4.0",
    "@typescript-eslint/parser": "5.4.0",
    "@vitejs/plugin-vue": "2.3.1",
    "@vue/eslint-config-typescript": "9.1.0",
    "eslint": "7.32.0",
    "eslint-config-prettier": "8.3.0",
    "eslint-plugin-prettier": "4.0.0",
    "eslint-plugin-vue": "8.0.3",
    "husky": "7.0.4",
    "is-ci": "3.0.1",
    "lint-staged": "11.1.2",
    "postcss": "^8.4.13",
    "postcss-html": "1.4.1",
    "prettier": "2.4.1",
    "sass": "1.51.0",
    "stylelint": "14.8.2",
    "stylelint-config-prettier": "9.0.3",
    "stylelint-config-recommended-vue": "1.4.0",
    "vite": "2.9.5",
    "yalc": "1.0.0-pre.53"
  },
  "lint-staged": {
    "*.{ts,vue}": "eslint --fix",
    "*.{scss,vue}": "stylelint --fix"
  },
  "packageManager": "yarn@3.2.0"
}
```

_stylelint.config.js_
```js
module.exports = {
  extends: [
    'stylelint-config-html',
    'stylelint-config-recommended-vue',
    'stylelint-config-prettier',
  ],
  // add your custom config here
  // https://stylelint.io/user-guide/configuration
  rules: {},
};

```

**Comment by theolavaux** [comment]
I'll try to give a repro link using Yarn 2 😄

**Comment by theolavaux** [comment]
It seems that it was related to Yarn 2, I went back to Yarn v1, set everything up and then switched back to Yarn 2 and it works now 🤷 

Thanks for you help!
