### ISSUE TITLE
Error: No rules found within configuration

### ISSUE THREAD

**Issue by agauniyal** [stylelint/stylelint#607]
```
> zen-audio-player@1.1.0 stylelint:css /home/agauniyal/projects/zen-audio-player.github.io
> stylelint css/*.css

Error: No rules found within configuration
    at exports.default (/home/agauniyal/projects/zen-audio-player.github.io/node_modules/stylelint/dist/utils/configurationError.js:8:13)
    at /home/agauniyal/projects/zen-audio-player.github.io/node_modules/stylelint/dist/postcssPlugin.js:69:45
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'stylelint:css' ]
2 info using npm@3.5.2
3 info using node@v5.3.0
4 verbose run-script [ 'prestylelint:css', 'stylelint:css', 'poststylelint:css' ]
5 info lifecycle zen-audio-player@1.1.0~prestylelint:css: zen-audio-player@1.1.0
6 silly lifecycle zen-audio-player@1.1.0~prestylelint:css: no script for prestylelint:css, continuing
7 info lifecycle zen-audio-player@1.1.0~stylelint:css: zen-audio-player@1.1.0
8 verbose lifecycle zen-audio-player@1.1.0~stylelint:css: unsafe-perm in lifecycle true
9 verbose lifecycle zen-audio-player@1.1.0~stylelint:css: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/agauniyal/projects/zen-audio-player.github.io/node_modules/.bin:/home/agauniyal/.npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
10 verbose lifecycle zen-audio-player@1.1.0~stylelint:css: CWD: /home/agauniyal/projects/zen-audio-player.github.io
11 silly lifecycle zen-audio-player@1.1.0~stylelint:css: Args: [ '-c', 'stylelint css/*.css' ]
12 silly lifecycle zen-audio-player@1.1.0~stylelint:css: Returned: code: 78  signal: null
13 info lifecycle zen-audio-player@1.1.0~stylelint:css: Failed to exec stylelint:css script
14 verbose stack Error: zen-audio-player@1.1.0 stylelint:css: `stylelint css/*.css`
14 verbose stack Exit status 78
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid zen-audio-player@1.1.0
16 verbose cwd /home/agauniyal/projects/zen-audio-player.github.io
17 error Linux 4.3.3-2-ARCH
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "stylelint:css"
19 error node v5.3.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error zen-audio-player@1.1.0 stylelint:css: `stylelint css/*.css`
22 error Exit status 78
23 error Failed at the zen-audio-player@1.1.0 stylelint:css script 'stylelint css/*.css'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the zen-audio-player package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     stylelint css/*.css
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs zen-audio-player
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls zen-audio-player
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

csslint package works well with same arguments - `csslint css/*.css` so it's definitely not related to directory issue. Here's my rc file : 

```json
{
  "at-rule-empty-line-before": "always",
  "at-rule-no-vendor-prefix": true,
  "block-closing-brace-newline-after": "always",
  "block-closing-brace-newline-before": "always-multi-line",
  "block-closing-brace-space-after": "always-single-line",
  "block-closing-brace-space-before": "always",
  "block-no-empty": true,
  "block-opening-brace-newline-after": "always-multi-line",
  "block-opening-brace-newline-before": "always-multi-line",
  "block-opening-brace-space-after": "always",
  "block-opening-brace-space-before": "always",
  "color-hex-case": "lower",
  "color-hex-length": "long",
  "color-no-hex": false,
  "color-no-invalid-hex": true,
  "color-no-named": true,
  "comment-empty-line-before": "always",
  "comment-whitespace-inside": "always",
  "declaration-bang-space-after": "never",
  "declaration-bang-space-before": "always",
  "declaration-block-no-single-line": false,
  "declaration-block-semicolon-newline-after": "always",
  "declaration-block-semicolon-newline-before": "never-multi-line",
  "declaration-block-semicolon-space-after": "always-single-line",
  "declaration-block-semicolon-space-before": "never-single-line",
  "declaration-block-single-line-max-declarations": 1,
  "declaration-colon-newline-after": "always-multi-line",
  "declaration-colon-space-after": "always",
  "declaration-colon-space-before": "never",
  "declaration-no-important": true,
  "function-calc-no-unspaced-operator": true,
  "function-comma-newline-after": "never-multi-line",
  "function-comma-newline-before": "never-multi-line",
  "function-comma-space-after": "always-single-line",
  "function-comma-space-before": "never",
  "function-linear-gradient-no-nonstandard-direction": true,
  "function-parentheses-newline-inside": "always-multi-line",
  "function-parentheses-space-inside": "never",
  "function-url-quotes": "double",
  "function-whitespace-after": "always",
  "indentation": 4,
  "max-empty-lines": 2,
  "max-line-length": 80,
  "media-feature-colon-space-after": "always",
  "media-feature-colon-space-before": "never",
  "media-feature-name-no-vendor-prefix": true,
  "media-feature-range-operator-space-after": "always",
  "media-feature-range-operator-space-before": "always",
  "media-query-list-comma-newline-after": "always-multi-line",
  "media-query-list-comma-newline-before": "never-multi-line",
  "media-query-list-comma-space-after": "always-single-line",
  "media-query-list-comma-space-before": "never",
  "media-query-parentheses-space-inside": "always",
  "no-eol-whitespace": true,
  "no-missing-eof-newline": true,
  "number-leading-zero": "always",
  "number-max-precision": 2,
  "number-no-trailing-zeros": true,
  "number-zero-length-no-unit": true,
  "property-no-vendor-prefix": true,
  "rule-nested-empty-line-before": "always-multi-line",
  "rule-no-duplicate-properties": true,
  "rule-no-shorthand-property-overrides": true,
  "rule-non-nested-empty-line-before": "always",
  "rule-trailing-semicolon": "always",
  "selector-combinator-space-after": "always",
  "selector-combinator-space-before": "always",
  "selector-list-comma-newline-after": "always-multi-line",
  "selector-list-comma-newline-before": "never-multi-line",
  "selector-list-comma-space-after": "always",
  "selector-list-comma-space-before": "never",
  "selector-no-id": false,
  "selector-no-type": false,
  "selector-no-universal": true,
  "selector-no-vendor-prefix": true,
  "selector-pseudo-element-colon-notation": "double",
  "selector-root-no-composition": true,
  "string-quotes": "double",
  "value-list-comma-newline-after": "always-multi-line",
  "value-list-comma-newline-before": "never-multi-line",
  "value-list-comma-space-after": "always-single-line",
  "value-list-comma-space-before": "never",
  "value-no-vendor-prefix": true
}
```

**Comment by agauniyal** [comment]
Btw what does `No rules found within configuration` even means? Found no rules in .stylelintrc or css file?

**Comment by jeddy3** [comment]
Hi. What version of stylelint are you running?

**Comment by agauniyal** [comment]
My package.json mentions `"stylelint": "3.2.x"`

**Comment by jeddy3** [comment]
Umm. Can you please try `./node_modules/.bin/stylelint --version` to double check that the version you have installed matches that of your package.json? As the `No rules found within configuration` error has popped up before when the new `3.0.0+` config syntax is used with stylelint `2.0.0-`.

If it doesn't match... try `npm install stylelint@latest`.

**Comment by agauniyal** [comment]
```
» ./node_modules/.bin/stylelint --version 
3.2.0
```

**Comment by jeddy3** [comment]
FYI, `No rules found within configuration` refers to the rules of your configuration object and not the rules of your CSS. So, we're trying to work out why the linter thinks your configuration object is empty...

Where is your `.stylelintrc` file located?

**Comment by agauniyal** [comment]
```
» tree -L 1 -a
.
├── bower_components
├── bower.json
├── CONTRIBUTING.md
├── css
├── .git
├── .gitignore
├── .htmlhintrc
├── img
├── index.html
├── js
├── .jshintrc
├── LICENSE
├── node_modules
├── npm-debug.log
├── package.json
├── README.md
├── robots.txt
├── sitemap.txt
├── .stylelintrc
├── test
└── .travis.yml
```

**Comment by agauniyal** [comment]
With empty .stylelintrc
```
Error: No configuration found
    at exports.default (/home/agauniyal/projects/zen-audio-player.github.io/node_modules/stylelint/dist/utils/configurationError.js:8:13)
    at /home/agauniyal/projects/zen-audio-player.github.io/node_modules/stylelint/dist/buildConfig.js:38:54
```

**Comment by agauniyal** [comment]
If someone wants to reproduce:

1. clone repo - `git clone https://github.com/agauniyal/zen-audio-player.github.io`
2. cd into repo
3. install stylelint - `npm install stylelint --save-dev`
4. add .stylelintrc with just 1 rule `{ "value-no-vendor-prefix": true }`
5. `npm update`
6. add `"stylelint:css": "stylelint css/*.css"` to scripts section in `package.json`
7. `npm run stylelint:css`

**Comment by agauniyal** [comment]
I installed stylelint globally, created a new `.stylelintrc` in my `$HOME` for fallback and then even this command failed - `» echo "a { color: pink; }" | stylelint`

```
Error: No rules found within configuration
    at exports.default (/home/agauniyal/.npm-global/lib/node_modules/stylelint/dist/utils/configurationError.js:8:13)
    at /home/agauniyal/.npm-global/lib/node_modules/stylelint/dist/postcssPlugin.js:69:45
```

**Comment by agauniyal** [comment]
Travis build fails so definitely not my machine - https://travis-ci.org/zen-audio-player/zen-audio-player.github.io/builds/100806883

**Comment by jeddy3** [comment]
Ha, it was staring us in the face all along... I just had to start working through the issue to see it.

You're missing the `"rules"` key within your config. Your config should read:

```json
{
  "rules": {
    "at-rule-empty-line-before": "always",
    "at-rule-no-vendor-prefix": true,
    "block-closing-brace-newline-after": "always",
    "block-closing-brace-newline-before": "always-multi-line",
    "block-closing-brace-space-after": "always-single-line",
    "block-closing-brace-space-before": "always",
    "block-no-empty": true,
    "block-opening-brace-newline-after": "always-multi-line",
    "block-opening-brace-newline-before": "always-multi-line",
    "block-opening-brace-space-after": "always",
    "block-opening-brace-space-before": "always",
    "color-hex-case": "lower",
    "color-hex-length": "long",
    "color-no-hex": false,
    "color-no-invalid-hex": true,
    "color-no-named": true,
    "comment-empty-line-before": "always",
    "comment-whitespace-inside": "always",
    "declaration-bang-space-after": "never",
    "declaration-bang-space-before": "always",
    "declaration-block-no-single-line": false,
    "declaration-block-semicolon-newline-after": "always",
    "declaration-block-semicolon-newline-before": "never-multi-line",
    "declaration-block-semicolon-space-after": "always-single-line",
    "declaration-block-semicolon-space-before": "never-single-line",
    "declaration-block-single-line-max-declarations": 1,
    "declaration-colon-newline-after": "always-multi-line",
    "declaration-colon-space-after": "always",
    "declaration-colon-space-before": "never",
    "declaration-no-important": true,
    "function-calc-no-unspaced-operator": true,
    "function-comma-newline-after": "never-multi-line",
    "function-comma-newline-before": "never-multi-line",
    "function-comma-space-after": "always-single-line",
    "function-comma-space-before": "never",
    "function-linear-gradient-no-nonstandard-direction": true,
    "function-parentheses-newline-inside": "always-multi-line",
    "function-parentheses-space-inside": "never",
    "function-url-quotes": "double",
    "function-whitespace-after": "always",
    "indentation": 4,
    "max-empty-lines": 2,
    "max-line-length": 80,
    "media-feature-colon-space-after": "always",
    "media-feature-colon-space-before": "never",
    "media-feature-name-no-vendor-prefix": true,
    "media-feature-range-operator-space-after": "always",
    "media-feature-range-operator-space-before": "always",
    "media-query-list-comma-newline-after": "always-multi-line",
    "media-query-list-comma-newline-before": "never-multi-line",
    "media-query-list-comma-space-after": "always-single-line",
    "media-query-list-comma-space-before": "never",
    "media-query-parentheses-space-inside": "always",
    "no-eol-whitespace": true,
    "no-missing-eof-newline": true,
    "number-leading-zero": "always",
    "number-max-precision": 2,
    "number-no-trailing-zeros": true,
    "number-zero-length-no-unit": true,
    "property-no-vendor-prefix": true,
    "rule-nested-empty-line-before": "always-multi-line",
    "rule-no-duplicate-properties": true,
    "rule-no-shorthand-property-overrides": true,
    "rule-non-nested-empty-line-before": "always",
    "rule-trailing-semicolon": "always",
    "selector-combinator-space-after": "always",
    "selector-combinator-space-before": "always",
    "selector-list-comma-newline-after": "always-multi-line",
    "selector-list-comma-newline-before": "never-multi-line",
    "selector-list-comma-space-after": "always",
    "selector-list-comma-space-before": "never",
    "selector-no-id": false,
    "selector-no-type": false,
    "selector-no-universal": true,
    "selector-no-vendor-prefix": true,
    "selector-pseudo-element-colon-notation": "double",
    "selector-root-no-composition": true,
    "string-quotes": "double",
    "value-list-comma-newline-after": "always-multi-line",
    "value-list-comma-newline-before": "never-multi-line",
    "value-list-comma-space-after": "always-single-line",
    "value-list-comma-space-before": "never",
    "value-no-vendor-prefix": true
  }
}
```

Thanks for your detailed reports btw. And sorry for not seeing the obvious from the very beginning.

FYI, the `"rules"` key is needed as there are other keys in the config e.g. 

```json
{
  "extends": "stylelint-config-suitcss",
  "plugins": [
    "stylelint-selector-bem-pattern"
  ],
  "rules": {
    "selector-bem-pattern": { "preset": "suit" }
  }
}
```

@davidtheclark Perhaps we can expand the error message to `No rules found within configuration. Have you used the "rules" key?`?

**Comment by agauniyal** [comment]
I feel so stupid. Anyways thanks for helping me :smile: .
Also can you update project readme here 

>To craft your own from the ground up, just learn about some rules. All of the rules are off by default, so you only have to learn about the rules you want to turn on and enforce. That way you can start small, growing your config over time as you have a chance to explore more of the rules. Alternately, **copy-paste this example configuration**, which lists all of stylelint's rules and their primary options, then remove (or turn off) the rules you don't want and edit the primary option of each rule to your liking.

I literally copied all the rules lol

**Comment by jeddy3** [comment]
> Also can you update project readme here

You're right, "copy-paste this _example configuration_" is misleading as it's not a valid config, rather a list of the rules.

Fixed in https://github.com/stylelint/stylelint/commit/0f50e94e1bd5803516444f1cc36885468c3656c9

I'll let @davidtheclark close this issue once the error message issue is decided upon.

**Comment by davidtheclark** [comment]
> No rules found within configuration. Have you used the "rules" key?

That's fine by me.
