### ISSUE TITLE
Prepare 16.0.0

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint#6930]
I think it's a good time to start a discussion about the next major version.

Ref:
- Previous major version (Feb 2023): https://github.com/stylelint/stylelint/releases/tag/15.0.0
- https://github.com/stylelint/stylelint/issues/6409
- [future-major milestone](https://github.com/stylelint/stylelint/milestone/20)

Included:
*TBD*

Discussed:
- #6740
- #5291

*Please suggest other topics with a comment if you have any ideas.*

**Comment by jeddy3** [comment]
I'm catching up on my notifications. Seeing all the releases and hard work done over the last few months is fantastic! 

> I think it's a good time to start a discussion about the next major version.

I agree, and with including https://github.com/stylelint/stylelint/issues/6740 & https://github.com/stylelint/stylelint/issues/5291.

Let's remove the deprecated rules in 16.0.0 now that community plugins are available. One of the original motivations for deprecating the stylistic rules was to aid our migration to ESM, as those rules are the bulk of the oldest parts of our codebase.

@ybiquitous As an aside, do you have admin rights [to recover](https://support.1password.com/recovery/) my Stylelint 1password account? Something is up with my secret key.

**Comment by ybiquitous** [comment]
@jeddy3 Welcome back! 😄 

I agree with removing the deprecated rules, and I just updated this issue description.

> As an aside, do you have admin rights [to recover](https://support.1password.com/recovery/) my Stylelint 1password account? Something is up with my secret key.

Oh..., I don't have any admin access to 1password and am unsure about 1password details. 😓

**Comment by ybiquitous** [comment]
@jeddy3 Thanks. I can access it as an admin. 👍🏼 

By the way, Can I invite @mattxwang? He has recently performed releasing work many times (also today).
If he can access Twitter, we can leave releasing work to him completely.

**Comment by jeddy3** [comment]
> By the way, can I invite @mattxwang?

Absolutely. You can invite him to Team Member's group with access to the shared vault. @mattxwang Thanks for doing the recent releases. You're doing a fantastic job!

**Comment by ybiquitous** [comment]
@mattxwang I've sent an invitation to your email on your profile page. Can you check it, please?

**Comment by ybiquitous** [comment]
I've added #6966 to the "Discussing" list.

**Comment by mattxwang** [comment]
> @mattxwang I've sent an invitation to your email on your profile page. Can you check it, please?

Thanks - just signed up with an account with my public email address!

**Comment by ybiquitous** [comment]
@mattxwang I've confirmed your account. Let me know if you're in trouble. 👍🏼

**Comment by mattxwang** [comment]
@ybiquitous should I have access to a shared vault? I don't see anything under my items in the UI.

**Comment by ybiquitous** [comment]
@mattxwang Oh, sorry! I forgot to assign you to the shared vault. 🙇🏼 Can you see it now?

**Comment by mattxwang** [comment]
Thanks @ybiquitous - it works now!

**Comment by mattxwang** [comment]
Sorry the permissions conversation got a bit off-target! To re-focus - I've started the removing deprecated rules process at #6979. @ybiquitous had a good suggestion of a `v16` branch, so I've created one: https://github.com/stylelint/stylelint/tree/v16

**Comment by ybiquitous** [comment]
Thanks for creating the `v16` branch, @mattxwang. 👍🏼 

Reminder: we may need to regularly merge changes on `main` into `v16` to reduce conflicts.

**Comment by jeddy3** [comment]
As the ball is rolling on this (https://github.com/stylelint/stylelint/pull/6979), I've converted the top post into a task list.

**Comment by Mouvedia** [comment]
concerning [futur-major](https://github.com/stylelint/stylelint/milestone/20)

- I also think that #5348 is low priority because it can easily be handled with `/*`/`*/`
- #6258 would require someone to decide what we ought to expose based on the usage [in the wild](https://github.com/search?q=%22stylelint%2Flib%2Futils%2F%22+language%3AJavaScript&type=code&l=JavaScript)
- #4989 is a breaking change, but the status should be changed to _needs investigation_ or _needs clarification_
- #​5042 should be added (see [rationale](https://github.com/stylelint/stylelint/issues/5042#issuecomment-1416791902))

**Comment by mattxwang** [comment]
Sorry for being a bit MIA, my work at NEU ended up being a bit more consuming than I thought. I have a couple of weeks before instruction starts where I can get into the nitty gritty. What could I best help out with? I know @ybiquitous has been doing a great job with ESM migration - would you like more reviews there and/or me to help with the migration?

Alternatively, I could start doing the rest of #6966, which could be done (almost) completely asynchronously, and could in theory be folded into future v15 releases.

**Comment by ybiquitous** [comment]
I've just added #7141 to the task list.

**Comment by Mouvedia** [comment]
I think that we should remove some issues so that we can merge v16 sooner.
**It has diverged way too much IMHO.**

- can be postponed to 16.1+
  - #6966: doesn't have to be finished, it's not blocker
  - #6258: would be cool to have, but it's not a must have for the major
- are medium to low priority
  - #5348
  - #7116

That would leave us with _only_ #5291 left; @ybiquitous is sure working hard towards its completion.
What do you think of dropping these 4 for now?

**Comment by ybiquitous** [comment]
Agree with @Mouvedia. These are not a blocker. I've updated the task list in <https://github.com/stylelint/stylelint/issues/6930#issue-1761875227>.

**Comment by mattxwang** [comment]
Agreed as well - I've been a bit behind on the `messageArgs` work. I think I need to spend quite a bit more time fleshing out how it works + how we'd document it. 

Perhaps this is good since our `17` can:

- drop Node 16
- address (some of) the various items in @Mouvedia's list above

And that can come out relatively quickly if necessary?

**Comment by Mouvedia** [comment]
Should we release a `-next` pre-release for v16?

**Comment by ybiquitous** [comment]
> Should we release a `-next` pre-release for v16?

Sounds good. I believe we can do that after merging the `v16` branch into `main`.

**Comment by Mouvedia** [comment]
> merging the `v16` branch into `main`

@ybiquitous is https://github.com/stylelint/stylelint/issues/5291#issuecomment-1713747157 all that's left to do for v16 to be ready? Is the test coverage lower?

> And that can come out relatively quickly if necessary?

Right now we only have the future-major label which holds issues that must be part of _a_ major release.
If we are planning to release v17 relatively quicker due to #7240 then we should rename `future-major` to `future-majors` and add a `next-major` label.

**Comment by Mouvedia** [comment]
- https://github.com/stylelint/stylelint/blob/4bd955d1b493e561d5c321de2ccad7469ddf3d71/.github/dependabot.yml#L25
- [ ] [warning](https://github.com/stylelint/stylelint/issues/5291#issuecomment-1604292676)
- #7240
  - [ ] #7289
  - [ ] #7288
  - [ ] #7160

**Comment by ybiquitous** [comment]
We should release a beta version for 16.0.0. Providing the `next` tag should be helpful. For example:

```shell
npm i stylelint@next
```

**Comment by jeddy3** [comment]
> We should release a beta version for 16.0.0.

SGTM. We [did it for `14`](https://www.npmjs.com/package/stylelint/v/14.0.0-0) as it also contained a significant change in the codebase.

**Comment by ybiquitous** [comment]
I believe we can publish the `next` version after we merge the following PRs on the `v16` branch:

- #7307 
- #7309 
- #7160
- #7002

Then, we should be able to return to the one branch (`main`) operation toward the 16.0.0 release.

**Comment by ybiquitous** [comment]
@Mouvedia I'm considering how to implement your suggestion: 🤔 

> Let's add one `console.warning` when the last or first cjs plugin is loaded.

https://github.com/stylelint/stylelint/issues/5291#issuecomment-1604292676

Do you have any specific idea?

**Comment by Mouvedia** [comment]
> Do you have any specific ideas?

I didn't verify if I am correct but maybe around here:

https://github.com/stylelint/stylelint/blob/cb0e7d299333d9d9e8c19d264642466aca6287eb/lib/augmentConfig.mjs#L328

**Comment by ybiquitous** [comment]
I've merged #7002 and deleted the `v16` branch. I'll release `16.0.0-0` (`next`) from now.

**Comment by ybiquitous** [comment]
Oops, I tried `npm run release -- --tag=next` but failed. See the log below. The error is due to `changeset version`. I'm finding a workaround...

```
? Select semver increment or specify new version premajor 	16.0.0-0

  ✔ Prerequisite check
  ✔ Git
  ✔ Installing dependencies using npm
  ✔ Running tests using npm
  ✖ Bumping version using npm
    → > changeset version
    Publishing package using npm
    Pushing tags

✖ Error: Command failed with exit code 1: npm version 16.0.0-0
(node:66086) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
The following error was encountered while generating changelog entries
We have escaped applying the changesets, and no files should have been affected
🦋  error Error: Please create a GitHub personal access token at https://github.com/settings/tokens/new with `read:user` and `repo:status` permissions and add it as the GITHUB_TOKEN environment variable
🦋  error     at /Users/masafumi.koba/git/stylelint/stylelint/node_modules/@changesets/get-github-info/dist/get-github-info.cjs.dev.js:156:11
🦋  error     at dispatchQueueBatch (/Users/masafumi.koba/git/stylelint/stylelint/node_modules/dataloader/index.js:246:22)
🦋  error     at dispatchQueue (/Users/masafumi.koba/git/stylelint/stylelint/node_modules/dataloader/index.js:233:5)
🦋  error     at /Users/masafumi.koba/git/stylelint/stylelint/node_modules/dataloader/index.js:70:20
🦋  error     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
npm ERR! code 1
npm ERR! path /Users/masafumi.koba/git/stylelint/stylelint
npm ERR! command failed
npm ERR! command sh -c changeset version

npm ERR! A complete log of this run can be found in: /Users/masafumi.koba/.npm/_logs/2023-11-10T14_35_48_061Z-debug-0.log

> version
> changeset version

    at makeError (file:///Users/masafumi.koba/git/stylelint/stylelint/node_modules/np/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///Users/masafumi.koba/git/stylelint/stylelint/node_modules/np/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Aborted!
```

**Comment by ybiquitous** [comment]
I'll commit the following change to skip `npm run version temporarily` before running the `npm run release` command:

```diff
-    "version": "changeset version",
+    "version": "echo \"skip: changeset version\"",
```

Also, I'll try the new repository ruleset instead of the branch protection rule, as I commented on <https://github.com/stylelint/stylelint/issues/7243#issuecomment-1768085181> (the previous release). If this new operation works, I'll reflect it to `docs/maintainer-guide/releases.md`.

**Comment by ybiquitous** [comment]
Done! 🎉 

- https://www.npmjs.com/package/stylelint/v/16.0.0-0
- https://github.com/stylelint/stylelint/releases/tag/16.0.0-0

You can install the pre-release version via:

```shell
npm i stylelint@next
```

Notice for maintainers:
- Run `npm run release -- --tag=next`.
- I've removed the old branch protection rule.
- I've updated the bypass list in the new repository ruleset (`main`).
  - The "Organization admin" role is added to the bypass list. Should we remove the role after the release? Or, keep it?

**Comment by chojnicki** [comment]
Great! Is there any specified period until `next` can become major version? Any ETA for release?

**Comment by ybiquitous** [comment]
@jeddy3 Thank you for the work. We still seem to have a few tasks toward 16.0.0.

For ESM plugins, I've just opened #7327. I didn't think supporting ESM plugins was a blocker, but many people might hope that. (#7267 or #7269 as well?)

In addition, if we'd like to make `stylelint` a pure ESM package, we may need to deprecate CJS in the 16.0.0 release.

**Comment by jeddy3** [comment]
> For ESM plugins, I've just opened https://github.com/stylelint/stylelint/issues/7327. I didn't think supporting ESM plugins was a blocker, but many people might hope that. (https://github.com/stylelint/stylelint/issues/7267 or https://github.com/stylelint/stylelint/issues/7269 as well?)

Yes, I think people might hope for ESM plugins, formatters and custom syntaxes. The `16.0.0` release seems like a good time to include these, as major releases are when people read the migration guide. It'll be our opportunity to explain how we're moving towards pure ESM and how plugin/formatter/syntax authors can start using ESM in their own code if they like.

Do you think it'll be viable to include them or is it another huge chunk of work?

> In addition, if we'd like to make stylelint a pure ESM package, we may need to deprecate CJS in the 16.0.0 release.

Do you mean deprecate CJS plugins, custom syntaxes etc or just `.cjs` config files? I think, although I'm not 100% sure, we can still dynamically import CJS plugins/syntaxes/formatters from ESM.

**Comment by jeddy3** [comment]
Thanks for the clarification.

If the stylelint package were to become pure ESM in 17.0.0, do we know what the breaking changes would be? It is just:

- commonjs config files 
- requiring `*.cjs` internal utils

Or do we think there'll be more? (I'm wondering as it'd be great to include some information in our `16.0.0` migration guide about the direction we're going in.)

**Comment by ybiquitous** [comment]
When turning into pure ESM, the biggest breaking change will be that `require('stylelint')` won't work anymore.

> * commonjs config files

I'm unsure, but this should depend on the Cosmiconfig behavior. If Cosmiconfig supports CJS, I guess CJS config files won't break.

> * requiring `*.cjs` internal utils

Correct. Specifically, `lib/index.cjs` and `lib/utils/*.cjs` files:
- https://github.com/stylelint/stylelint/blob/613e8f949bf97f75ae1af50d7b4af2bece3b03d1/package.json#L31
- https://github.com/stylelint/stylelint/blob/613e8f949bf97f75ae1af50d7b4af2bece3b03d1/package.json#L34

> I'm wondering as it'd be great to include some information in our `16.0.0` migration guide about the direction we're going in.

Absolutely agree 👍🏼

**Comment by firefoxic** [comment]
I'm sorry, maybe I'm asking in the wrong place. But I really want to be clear: will [this guide](https://github.com/stylelint/stylelint/blob/main/docs/developer-guide/plugins.md) be updated before release?

Without it, now I have to pick through a huge diff between `16.0.0-0` and `15.11.0` to understand why my plugin fails rule tests. All the other code is already prepared and the tests work, only the rules are in trouble and the guide doesn't help at all, neither does the migration guide.

**Comment by ybiquitous** [comment]
@firefoxic Thanks for the feedback. Can you share a link to your problem?

**Comment by firefoxic** [comment]
> Can you share a link to your problem?

Not yet, I'm preparing a plugin for stylelint@16 locally right now. Maybe I should push a WIP-commit…

**Comment by ybiquitous** [comment]
Okay. If you will be ready to share your problem with a specific code, can you open a new issue, please? We're glad to improve the v16 migration guide and the existing documents.

**Comment by jeddy3** [comment]
> Not yet, I'm preparing a plugin for stylelint@16 locally right now. Maybe I should push a WIP-commit…

@firefoxic Thanks for preparing your plugin and testing the prerelease of 16! As @ybiquitous said, we're looking for feedback on how to improve our docs and our migration guide ([which is WIP here](https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-16.md)), any help pointers are appreciated .

**Comment by jeddy3** [comment]
> And that's not the case now, is it? 😲

We've just opened an issue to track that: https://github.com/stylelint/stylelint/issues/7327

A lot of work has been done to move the codebase to a hybrid ESM/CJS one. We haven't yet added new features on top of it, though.

**Comment by firefoxic** [comment]
> Can you share a link to your problem?

After double-checking everything again and leaving babel and build, I left only the necessary to upgrade to stylelint@16 in the last commit. I didn't miss anything, but it's in this [commit that the tests fail](https://github.com/firefoxic/stylelint-codeguide/pull/6).

I haven't realized yet what I did wrong, or what's missing in the guides. But in almost all the dropped tests, I see that Stylelint did not add the rules from the plugin to its list.

**Comment by ybiquitous** [comment]
https://github.com/stylelint/stylelint/releases/tag/16.0.0-2 is out! The main change is the addition of ESM plugin support (#7339).

**Comment by jeddy3** [comment]
I've begun migrating [stylelint-scales](https://github.com/jeddy3/stylelint-scales/) to ESM to test our latest prerelease and to check if anything needs to be added to our migration guide for plugin authors. It was mostly smooth going, but there were a few oddities.

1\. I followed the [latest plugin example](https://github.com/stylelint/stylelint/blob/main/docs/developer-guide/plugins.md#the-anatomy-of-a-plugin), [and used](https://github.com/jeddy3/stylelint-scales/pull/94/files#diff-76b27f6d7cea79eea61c6c7a1fac93a9acb9ace0b0228f195031f8a365b48a20R115-R119) this export structure:

```js
rule.ruleName = ruleName;
rule.messages = messages;
rule.meta = meta;

export default createPlugin(ruleName, rule);
```

I [now have to destructure the _nested_ rule object](https://github.com/jeddy3/stylelint-scales/pull/94/files#diff-3b5a9cc5bd721b8978dd65909491ee9e235cd30ecf39ebf719b898a843a177b1) in my tests:

```diff js
- const { messages, ruleName } = require("..");
+ import rule from "../index.js";
+ const {
+  rule: { messages, ruleName },
+ } = rule;
```

Because it has this signature:

```console
{
  ruleName: 'scales/alpha-values',
  rule: [Function: rule] {
    primaryOptionArray: true,
    ruleName: 'scales/alpha-values',
    messages: { expected: [Function (anonymous)] },
    meta: {
      url: 'https://github.com/jeddy3/stylelint-scales/blob/main/lib/rules/alpha-values/README.md',
      fixable: true
    }
  }
}
```

Does that nested structure look right? It seems off.

2\. I was slightly thrown when setting up our Jest preset as I had to [update the path](https://github.com/jeddy3/stylelint-scales/pull/94/files#diff-4c3cfde2c8298e64ca709feb98ce653c1f25d523dc113f5fc097d9314ec785efR3).

```diff js
- global.testRule = getTestRule({ plugins: ["./"] });
+ global.testRule = getTestRule({ plugins: ["./lib/index.js"] });
```

I assume this has something to do with [change from `main` to `exports`](https://github.com/jeddy3/stylelint-scales/pull/94/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L6-R6):

```diff json
{
-  "main": "lib/index.js",
+  "exports": "./lib/index.js",
}
```

Did I get something wrong? If not, we'll want to add something to the migration guide as part of https://github.com/stylelint/stylelint/issues/7340.

3\. Lastly, Jest is [tripping up](https://github.com/jeddy3/stylelint-scales/pull/94) on Windows and Node.js@18 on *nix.

*nix:

```console
A jest worker process (pid=2039) was terminated by another process: signal=SIGSEGV, exitCode=null. Operating system logs may contain more information on why this occurred.
```

Windows:

```console
D:\a\stylelint-scales\stylelint-scales\node_modules\.bin\jest:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
```

@ybiquitous Did you encounter either of these when migrating the tests for Stylelint's built-in rules to ESM?

**Comment by ybiquitous** [comment]
@jeddy3 Thanks for trying. I answer them below.

> 1. I followed the latest plugin example, and used this export structure:

Yes, right. The previous code in CJS is incorrect:

```js
module.exports = createPlugin(ruleName, rule);
module.exports.ruleName = ruleName;
module.exports.messages = messages;
```

should have been:

```js
rule.ruleName = ruleName;
rule.messages = messages;
module.exports = createPlugin(ruleName, rule);
```

However, because the `ruleName` and `messages` have not been used in the user-facing area, I guess no problems would have occurred.

The new code in ESM is correct. 👌🏼

For your information, I share the following type definitions with **15.11.0** for a plugin and rule. They will not change with 16.0.0, too:

- https://github.com/stylelint/stylelint/blob/8914d463e6e2622ba0d82ae69d36e61f3c08eb89/types/stylelint/index.d.ts#L72
- https://github.com/stylelint/stylelint/blob/8914d463e6e2622ba0d82ae69d36e61f3c08eb89/types/stylelint/index.d.ts#L221-L226

---

> 2. I was slightly thrown when setting up our Jest preset as I had to update the path.

The change to `exports` is correct. I agree with the addition to the migration guide. 👍🏼 

> 3. Lastly, Jest is tripping up on Windows and Node.js@18 on *nix.

For the `SIGSEGV` error (segmentation fault), #7329 seems to be related, but I'm not 100% sure at this time. 🤔 

And I'm unsure about the `SyntaxError` on Windows. I also will look into your plugin code.

**Comment by Mouvedia** [comment]
## concerning 2.

> Replace "main": "index.js" with "exports": "./index.js" in your package.json.

This should be removed. It's not necessary; it's equivalent but slightly less compatible with other tools that might only pick up `main`.

You should add a note saying that a dual ESM/CJS plugin that would target stylelint ≥15 would require _both_ `exports` and `main`. The reason being #6477, which pushed the minimum node version above 13.
i.e. [`exports` was introduced in version 13](https://nodejs.org/docs/latest-v13.x/api/esm.html#esm_package_entry_points)

**Comment by ybiquitous** [comment]
@Mouvedia For <https://github.com/stylelint/stylelint/issues/6930#issuecomment-1813849262>, can you please comment on #7340? There are so many comments already on this issue.

**Comment by newives** [comment]
May I ask when the official version will be released?

**Comment by firefoxic** [comment]
I may sound silly, but watching all the things you have to do for a dual module system makes me feel sorry for your efforts. It seems like it would be much easier for you to switch completely to pure ESM in version 16, and declare version 15 as LTS for a year (or two), which you maintain in a separate branch, releasing only patches with bug fixes, maybe one or two minor versions.

Although I feel sorry for the effort you've spent, because you'll remove it all in the next major version anyway, at the same time I admire the work you've done ♥️

**Comment by jeddy3** [comment]
> I believe it should be the last significant PR toward 16.0.0.

Yes, I agree. We can put another another prerelease, do some more local testing and give the documentation the once over, and then I think we're about ready to release! 🚀

**Comment by newives** [comment]
@ybiquitous Thank you so much for your work, love you so much

**Comment by firefoxic** [comment]
Is the idea of creating a `testRule` using `node:test` shelved for now?

**Comment by ybiquitous** [comment]
@firefoxic Thanks for the reminder. I've just created the repository, although it's still blank: <https://github.com/stylelint/stylelint-test-rule-node>. Please let us know if you want to contribute to the new package.

Ref https://github.com/stylelint/stylelint/issues/7340#issuecomment-1816300733

**Comment by ybiquitous** [comment]
@firefoxic Thanks a lot for the feedback. I'm also concerned about the change. Can you share where I can look into the failure? (tests on firefoxic/stylelint-codeguide#6 seems successful)

**Comment by firefoxic** [comment]
> Can you share where I can look into the failure? (tests on [firefoxic/stylelint-codeguide#6](https://github.com/firefoxic/stylelint-codeguide/pull/6) seems successful)

Yeah, sure. Habit of not pushing until fixed 🤭

**Comment by firefoxic** [comment]
> I could only find empty sets of custom properties (such as `:root { --foo: {}; }`), tests with them don't fail.

My assumption was wrong — it's not about an empty set, because there is one set that is not empty:

![Screenshot from 2023-12-01 15-39-15@2x](https://github.com/stylelint/stylelint/assets/3382798/b7d013cd-be50-4d88-811f-fb6fc392cfe5)

It's about the `fix` option, because the code breaks when you enable it.

And still, the question is relevant for me: why do we need code samples in tests with invalid CSS syntax and without specifying `customSyntax`? Maybe we should get rid of them altogether? Or at least move them to separate tests with the corresponding `customSyntax`?

**Comment by firefoxic** [comment]
If `node@14` is no longer supported, maybe fix this [deprecated flag](https://docs.npmjs.com/cli/v10/commands/npm-exec#:~:text=The%20%2D%2Dno%2Dinstall%20option%20is%20deprecated%2C%20and%20will%20be%20converted%20to%20%2D%2Dno.) too?

https://github.com/stylelint/stylelint/blob/a83af3eb88551b524a5bccd0f2bb3adbcaf9c053/.husky/pre-commit#L6

And by the way, have you considered switching to `pnpm`?

**Comment by ybiquitous** [comment]
@firefoxic 

> If `node@14` is no longer supported, maybe fix this [deprecated flag](https://docs.npmjs.com/cli/v10/commands/npm-exec#:~:text=The%20%2D%2Dno%2Dinstall%20option%20is%20deprecated%2C%20and%20will%20be%20converted%20to%20%2D%2Dno.) too?

Good catch. Can you open PR to change the flag if you have time?

> have you considered switching to `pnpm`?

As I remember, there are no issues, but a related one is #6298. You can freely open a issue to suggest `pnpm` if you have a strong opinion.

**Comment by Mouvedia** [comment]
@firefoxic https://github.com/stylelint/stylelint/issues/6930#issuecomment-1834532783 is not a blocker for v16?

**Comment by firefoxic** [comment]
Not anymore. I removed those tests with non-standard syntax from the plugin. If such tests don't fail in Stylelint, it's probably not critical.
