### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '.js')

### ISSUE THREAD

**Issue by muuvmuuv** [stylelint/stylelint#7086]
### What minimal example or steps are needed to reproduce the bug?

Just run the command

### What minimal configuration is needed to reproduce the bug?

Any config with an extend in it

### How did you run Stylelint?

```shell
pnpm stylelint --ignore-path .gitignore 'src/**/*.{css,scss}'
```

### Which Stylelint-related dependencies are you using?

```json
{
    "stylelint": "^15.10.1",
    "stylelint-config-clean-order": "^5.0.1",
    "stylelint-config-standard-scss": "^10.0.0",
}
```

<details>
<summary>`pnpm why cosmiconfig`</summary>

```
stylelint 15.10.1
└── cosmiconfig 8.1.3
stylelint-config-clean-order 5.0.1
├─┬ stylelint 15.10.1 peer
│ └── cosmiconfig 8.1.3
└─┬ stylelint-order 6.0.3
  └─┬ stylelint 15.10.1 peer
    └── cosmiconfig 8.1.3
stylelint-config-standard-scss 10.0.0
├─┬ stylelint 15.10.1 peer
│ └── cosmiconfig 8.1.3
├─┬ stylelint-config-recommended-scss 12.0.0
│ ├─┬ stylelint 15.10.1 peer
│ │ └── cosmiconfig 8.1.3
│ ├─┬ stylelint-config-recommended 12.0.0
│ │ └─┬ stylelint 15.10.1 peer
│ │   └── cosmiconfig 8.1.3
│ └─┬ stylelint-scss 5.0.1
│   └─┬ stylelint 15.10.1 peer
│     └── cosmiconfig 8.1.3
└─┬ stylelint-config-standard 33.0.0
  ├─┬ stylelint 15.10.1 peer
  │ └── cosmiconfig 8.1.3
  └─┬ stylelint-config-recommended 12.0.0
    └─┬ stylelint 15.10.1 peer
      └── cosmiconfig 8.1.3
```

</details>

### What did you expect to happen?

Resolves without error

### What actually happened?

```
TypeError: Cannot read properties of undefined (reading '.js')
    at .js (/Users/marvin/Developer/PROJECT/PROJECT/node_modules/.pnpm/stylelint@15.10.1/node_modules/stylelint/lib/createStylelint.js:26:40)
    at Explorer.loadFileContent (/Users/marvin/Developer/PROJECT/PROJECT/node_modules/.pnpm/cosmiconfig@8.1.3/node_modules/cosmiconfig/dist/Explorer.js:90:20)
    at Explorer.createCosmiconfigResult (/Users/marvin/Developer/PROJECT/PROJECT/node_modules/.pnpm/cosmiconfig@8.1.3/node_modules/cosmiconfig/dist/Explorer.js:98:36)
    at runLoad (/Users/marvin/Developer/PROJECT/PROJECT/node_modules/.pnpm/cosmiconfig@8.1.3/node_modules/cosmiconfig/dist/Explorer.js:115:33)
    at async cacheWrapper (/Users/marvin/Developer/PROJECT/PROJECT/node_modules/.pnpm/cosmiconfig@8.1.3/node_modules/cosmiconfig/dist/cacheWrapper.js:16:18)
    at async extendConfig (/Users/marvin/Developer/PROJECT/PROJECT/node_modules/.pnpm/stylelint@15.10.1/node_modules/stylelint/lib/augmentConfig.js:184:19)
    at async augmentConfigBasic (/Users/marvin/Developer/PROJECT/PROJECT/node_modules/.pnpm/stylelint@15.10.1/node_modules/stylelint/lib/augmentConfig.js:57:20)
    at async augmentConfigFull (/Users/marvin/Developer/PROJECT/PROJECT/node_modules/.pnpm/stylelint@15.10.1/node_modules/stylelint/lib/augmentConfig.js:111:24)
    at async run (/Users/marvin/Developer/PROJECT/PROJECT/node_modules/.pnpm/cosmiconfig@8.1.3/node_modules/cosmiconfig/dist/Explorer.js:48:14)
    at async cacheWrapper (/Users/marvin/Developer/PROJECT/PROJECT/node_modules/.pnpm/cosmiconfig@8.1.3/node_modules/cosmiconfig/dist/cacheWrapper.js:16:18)
```

### Do you have a proposal to fix the bug?

`cosmiconfig` exports "defaultLoaders" without the "sync".

https://github.com/stylelint/stylelint/blob/main/lib/createStylelint.js#L3C22-L3C40

**Comment by romainmenke** [comment]
Hi @muuvmuuv,
Thank you for the issue.

From the report I see that you have `cosmiconfig` version `8.1.3`.
But [`stylelint` requires version `^8.2.0`](https://github.com/stylelint/stylelint/blob/main/package.json#L141).

Can you try updating?

**Comment by muuvmuuv** [comment]
I just updated all my deps, let me check my lockfile. Kinda weird that the resolution is wrong here.

**Comment by muuvmuuv** [comment]
Ohhh, someone forced override the version... I am sorry didn't checked that
