### ISSUE TITLE
Could not find "stylelint-config-standard". Do you need the "configBasedir" or "--config-basedir" option?

### ISSUE THREAD

**Issue by jcubic** [stylelint/stylelint#7445]
### Describe the documentation issue

What is needed to run the tool? The documentation says that you can use:

```
npx stylelint "**/*.css"
```

But I got this error instead.

```
Error: Could not find "stylelint-config-standard". Do you need the "configBasedir" or "--config-basedir" option?
    at configurationError (file:///home/kuba/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/utils/configurationError.mjs:12:49)
    at getModulePath (file:///home/kuba/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/utils/getModulePath.mjs:29:9)
    at loadExtendedConfig (file:///home/kuba/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/augmentConfig.mjs:217:21)
    at extendConfig (file:///home/kuba/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/augmentConfig.mjs:185:25)
    at augmentConfigBasic (file:///home/kuba/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/augmentConfig.mjs:58:26)
    at augmentConfigFull (file:///home/kuba/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/augmentConfig.mjs:112:30)
    at Object.transform (file:///home/kuba/.npm/_npx/69cd2ba96dd4b8d2/node_modules/stylelint/lib/getConfigForFile.mjs:52:37)
    at search (/home/kuba/.npm/_npx/69cd2ba96dd4b8d2/node_modules/cosmiconfig/dist/Explorer.js:53:54)
    at async search (/home/kuba/.npm/_npx/69cd2ba96dd4b8d2/node_modules/cosmiconfig/dist/Explorer.js:71:28)
    at async search (/home/kuba/.npm/_npx/69cd2ba96dd4b8d2/node_modules/cosmiconfig/dist/Explorer.js:71:28)
```

### What solution would you like to see?

How to use the tool? Do I need a configuration file? Docs don't say you need it:

https://stylelint.io/user-guide/cli

It seems that you need to run `npm init stylelint` I would add this to CLI documentation as well.

**Comment by jcubic** [comment]
I think that I had some old config file in the project.
