### ISSUE TITLE
Missed semicolon CssSyntaxError in shadow-offset property.

### ISSUE THREAD

**Issue by carloslibardo** [stylelint/stylelint#7537]
### What minimal example or steps are needed to reproduce the bug?

my component in styles.ts:

```ts
export const ButtonContainer = styled.View.attrs({ elevation: 15 })`
  background-color: ${({ theme: { COLORS } }) => COLORS.BACKGROUND};
  padding-horizontal: 24px;
  padding-vertical: 30px;
  shadow-offset: {width: 0, height: 2};
  shadow-opacity: 0.3;
  shadow-radius: 2px;
  shadow-color: #0000004D;
`;
```

The problem is at  shadow-offset: {width: 0, height: 2};

### What minimal configuration is needed to reproduce the bug?

my .stylelintrc:

```json
{
    "processors": ["stylelint-processor-styled-components"],
    "extends": ["stylelint-config-react-native-styled-components"],
    "plugins": ["stylelint-react-native"],
    "customSyntax": "postcss-styled-syntax"
}
```

### How did you run Stylelint?

`stylelint './src/**/*.ts`

### Which Stylelint-related dependencies are you using?

```json
    "stylelint": "^16.2.1",
    "stylelint-config-react-native-styled-components": "^0.7.0",
    "stylelint-processor-styled-components": "^1.10.0",
    "stylelint-react-native": "^2.7.0",
    "postcss-styled-syntax": "^0.6.4",
    
```

### What did you expect to happen?

stylelint works without error.

### What actually happened?

I'm getting this error:  `Missed semicolon  CssSyntaxError`

**Comment by ybiquitous** [comment]
@carloslibardo Thanks for the report with a reproducible demo. I am afraid, but this problem seems to be caused by [`postcss-styled-syntax`](https://github.com/hudochenkov/postcss-styled-syntax) rather than Stylelint. See the reproduction:

`package.json`:

```json
{
  "dependencies": {
    "postcss-styled-syntax": "0.6.4"
  }
}
```

`parse.mjs`:

```js
import s from "postcss-styled-syntax";

const code = "const Component = styled.div`prop: {x: 1, y: 2};`";

s.parse(code);
```

Run:

```sh-session
$ node parse.mjs
/Users/masafumi/tmp/foo/node_modules/postcss/lib/input.js:106
      result = new CssSyntaxError(
               ^

CssSyntaxError: <css input>:1:42: Missed semicolon
    at Input.error (/Users/masafumi/tmp/foo/node_modules/postcss/lib/input.js:106:16)
    at Parser.checkMissedSemicolon (/Users/masafumi/tmp/foo/node_modules/postcss/lib/parser.js:138:22)
    at Parser.decl (/Users/masafumi/tmp/foo/node_modules/postcss-styled-syntax/lib/parser.js:333:9)
    at Parser.other (/Users/masafumi/tmp/foo/node_modules/postcss-styled-syntax/lib/parser.js:170:9)
    at Parser.parse (/Users/masafumi/tmp/foo/node_modules/postcss-styled-syntax/lib/parser.js:86:12)
    at Object.parse (/Users/masafumi/tmp/foo/node_modules/postcss-styled-syntax/lib/parse.js:50:10)
    at file:///Users/masafumi/tmp/foo/parse.mjs:5:3
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7) {
  reason: 'Missed semicolon',
  source: 'prop: {x: 1, y: 2};',
  line: 1,
  column: 42,
  input: {
    column: 42,
    endColumn: undefined,
    endLine: undefined,
    line: 1,
    source: 'prop: {x: 1, y: 2};'
  }
}

Node.js v21.6.2
```

So, I suggest opening an issue in the `postcss-styled-syntax` repository.

cc @hudochenkov
