### ISSUE TITLE
Error upgrading from v16.2.1 to v16.3.0: No configuration provided

### ISSUE THREAD

**Issue by darrinmn9** [stylelint/stylelint#7577]
### What minimal example or steps are needed to reproduce the bug?

upon upgrading from `v16.2.1` -> `v16.3.0` (no other code/dependencies were changed), i get this error when linting files with stylelint

```
yarn stylelint --fix --allow-empty-input '**/*.{vue,css,scss}'

Error: No configuration provided for /app/src/app.vue
    at configurationError (file:///app/node_modules/stylelint/lib/utils/configurationError.mjs:12:49)
    at getConfigForFile (file:///app/node_modules/stylelint/lib/getConfigForFile.mjs:67:4)
    at async isPathIgnored (file:///app/node_modules/stylelint/lib/isPathIgnored.mjs:23:17)
    at async lintSource (file:///app/node_modules/stylelint/lib/lintSource.mjs:43:20)
    at async file:///app/node_modules/stylelint/lib/standalone.mjs:214:27
    at async Promise.all (index 0)
    at async standalone (file:///app/node_modules/stylelint/lib/standalone.mjs:257:22)
error Command failed with exit code 78.

```

### What minimal configuration is needed to reproduce the bug?

```
// stylelint.config.js
module.exports = {
  extends: [
    'stylelint-config-standard-scss',
    'stylelint-config-standard-vue/scss',
    'stylelint-config-recess-order',
    'stylelint-config-css-modules',
  ],
  rules: {},
}
```

### How did you run Stylelint?

`yarn stylelint --fix --allow-empty-input '**/*.{vue,css,scss}'`

### Which Stylelint-related dependencies are you using?

```
    "stylelint": "16.3.0",
    "stylelint-config-css-modules": "^4.1.0",
    "stylelint-config-recess-order": "^4.0.0",
    "stylelint-config-standard-scss": "^12.0.0",
    "stylelint-config-standard-vue": "^1.0.0",
    "stylelint-scss": "^6.0.0",
```

### What did you expect to happen?

No error upon the minor upgrade from `v16.2.1` -> `v16.3.0` (no other dependencies were changed)

### What actually happened?

```
yarn stylelint --fix --allow-empty-input '**/*.{vue,css,scss}'

Error: No configuration provided for /app/src/app.vue
    at configurationError (file:///app/node_modules/stylelint/lib/utils/configurationError.mjs:12:49)
    at getConfigForFile (file:///app/node_modules/stylelint/lib/getConfigForFile.mjs:67:4)
    at async isPathIgnored (file:///app/node_modules/stylelint/lib/isPathIgnored.mjs:23:17)
    at async lintSource (file:///app/node_modules/stylelint/lib/lintSource.mjs:43:20)
    at async file:///app/node_modules/stylelint/lib/standalone.mjs:214:27
    at async Promise.all (index 0)
    at async standalone (file:///app/node_modules/stylelint/lib/standalone.mjs:257:22)
error Command failed with exit code 78.

```

**Comment by Mouvedia** [comment]
`configForFile` calls `augmentConfigFull` which may call `augmentConfigBasic` which calls `absolutizePaths` which may call `getModulePath` which has changed in the version.
That's what I would investigate first.

@JounQin do you think that's related?

**Comment by ybiquitous** [comment]
Related to #7576

**Comment by ybiquitous** [comment]
Thanks for the report. Here's a reproducible [demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYBfEAaEAzAlgDYwBySAtnIjAB4UAOxAdGAM6vbgQB2BA5ghDAAOtxQphIWgBcY3KK0nwUAbVHjxk1tICexQvm7SAtJF74+x7UnlIATlGMA3AK4wA9KzaKQ6lAF1RTBwzfgAxCDtyJGlBACtWHk5Yeg5EETEJEG09GAMjJSyARgA2JgBmJgAGSSw-LV19QxNQiytpGyh7R1cYQslCGJhtSSCQdCA), which raises:

```
Cannot read properties of undefined (reading 'ignoreFiles')
```

**Comment by daniluk4000** [comment]
I can confirm this is fixed for us

**Comment by darrinmn9** [comment]
great job on such a quick fix! Thank you all so much for everything you do to make stylelint awesome!
