### ISSUE TITLE
DeprecationWarning: fs.Stats constructor is deprecated

### ISSUE THREAD

**Issue by doberkofler** [stylelint/stylelint#7680]
### What is the problem you're trying to solve?

When running stylelint on nodejs 22.1.0 i get the following warning: 
```
(node:57276) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
    at tryStatSync (file:///Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/@dual-bundle/import-meta-resolve/lib/resolve.js:139:12)
    at packageResolve (file:///Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/@dual-bundle/import-meta-resolve/lib/resolve.js:1002:18)
    at moduleResolve (file:///Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/@dual-bundle/import-meta-resolve/lib/resolve.js:1101:20)
    at defaultResolve (file:///Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/@dual-bundle/import-meta-resolve/lib/resolve.js:1266:15)
    at resolve (file:///Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/@dual-bundle/import-meta-resolve/index.js:32:12)
    at resolveSilent (file:///Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/stylelint/lib/utils/resolveSilent.mjs:49:35)
    at getModulePath (file:///Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/stylelint/lib/utils/getModulePath.mjs:18:13)
    at loadExtendedConfig (file:///Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/stylelint/lib/augmentConfig.mjs:230:21)
    at extendConfig (file:///Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/stylelint/lib/augmentConfig.mjs:198:25)
    at augmentConfigBasic (file:///Users/doberkofler/MyDev/ljs_app/trunk/periscope/node_modules/stylelint/lib/augmentConfig.mjs:60:26)
```

### What solution would you like to see?

It would be nice to get rid of the warning

**Comment by Mouvedia** [comment]
We can patch the dependency if versions <14.17.0 are supported by `@dual-bundle/import-meta-resolve`.
i.e. `return statSync(path, { throwIfNoEntry: false })`

**Comment by ybiquitous** [comment]
cc @JounQin

**Comment by JounQin** [comment]
Sorry for the delay, I'll do it tomorrow.

**Comment by JounQin** [comment]
`@dual-bundle/import-meta-resolve@4.1.0` has been released.

cc @doberkofler

**Comment by ybiquitous** [comment]
@JounQin Thanks for the new release! I just triggered Dependabot, and PR #7683 should resolve this issue.

Of course, even without PR #7638, you can update `@dual-bundle/import-meta-resolve` in your dependency tree via:

```shell
npm update @dual-bundle/import-meta-resolve
```

**Comment by creative2115** [comment]
hello, there!
on my pc, it is happened same problem as above.
I am trying to fix error.
