### ISSUE TITLE
emptyLineBefore option causes error in declaration-block-properties-order when a specified property is succeeded by an unspecified one

### ISSUE THREAD

**Issue by ethyde** [stylelint/stylelint#887]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?
I have this error : 

```
TypeError: Cannot read property 'separatedGroup' of undefined
```

> Which rule, if any, is this issue related to?

With the rule ```declaration-block-properties-order``` 

> What stylelint configuration is needed to reproduce this issue?

if i use ```"declaration-block-properties-order":["padding", "padding-top", "padding-right", "padding-bottom", "padding-left", "color"]``` It's work, but with : 
```json
{
  "rules": {
    "declaration-block-properties-order":[
  {
    emptyLineBefore: "always",
    properties: [
      "height",
      "width",
    ],
  },
  {
    emptyLineBefore: "always",
    properties: [
      "font-size",
      "font-weight",
    ],
  },
]
  }
}
```

> Which version of stylelint are you using?

4.5.1

> How are you running stylelint: CLI, PostCSS plugin, Node API?

I use CLI in npm script like : 
```
"csslint": "stylelint app/styles/modules/*.css --config conf/.stylelintrc"
```

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

No, normal css

> What did you expect to happen?

linting process should not error

> What actually happened (e.g. what warnings or errors you are getting)?

```
TypeError: Cannot read property 'separatedGroup' of undefined
    at checkOrder (S:\wamp\www\LABS\ETHYDELABS\bijoo-start\node_modules\stylelint\dist\rules\declaration-block-properties-order\index.js:122:85)
    at S:\wamp\www\LABS\ETHYDELABS\bijoo-start\node_modules\stylelint\dist\rules\declaration-block-properties-order\index.js:91:97
    at Rule.each (S:\wamp\www\LABS\ETHYDELABS\bijoo-start\node_modules\postcss\lib\container.js:60:22)
    at checkNode (S:\wamp\www\LABS\ETHYDELABS\bijoo-start\node_modules\stylelint\dist\rules\declaration-block-properties-order\index.js:50:12)
    at S:\wamp\www\LABS\ETHYDELABS\bijoo-start\node_modules\stylelint\dist\rules\declaration-block-properties-order\index.js:55:11
    at Rule.each (S:\wamp\www\LABS\ETHYDELABS\bijoo-start\node_modules\postcss\lib\container.js:60:22)
    at checkNode (S:\wamp\www\LABS\ETHYDELABS\bijoo-start\node_modules\stylelint\dist\rules\declaration-block-properties-order\index.js:50:12)
    at S:\wamp\www\LABS\ETHYDELABS\bijoo-start\node_modules\stylelint\dist\rules\declaration-block-properties-order\index.js:42:9
    at Root.each (S:\wamp\www\LABS\ETHYDELABS\bijoo-start\node_modules\postcss\lib\container.js:60:22)
    at S:\wamp\www\LABS\ETHYDELABS\bijoo-start\node_modules\stylelint\dist\rules\declaration-block-properties-order\index.js:40:10
```

**Comment by jeddy3** [comment]
Confirmed. Thanks for the report.

Tracked it down to if a *specified* property is succeeded by an *unspecified* one  e.g. for the above config: 

```css
a {
  height: 0;
  top: 0; /* is unspecified */
}
```

**Comment by davidtheclark** [comment]
Fixed released in v5.
