### ISSUE TITLE
Unable to run in environments without eval

### ISSUE THREAD

**Issue by Arcanemagus** [stylelint/stylelint#891]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

This is ultimately https://github.com/One-com/one-color/issues/22, but as `onecolor` is a dependency of pipetteur, which is a dependency of the colorguard dependency added in https://github.com/stylelint/stylelint/commit/0e2bf25d9d02a13d679d872194d46d03f6d5884d, this is affecting `stylelint`.

> Which version of stylelint are you using?

v4.5.1

> How are you running stylelint: CLI, PostCSS plugin, Node API?

Through the Node API within Atom.

> What did you expect to happen?

No errors being thrown.

> What actually happened (e.g. what warnings or errors you are getting)?

The following error is being thrown:
```text
     EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
      at Function (native)
      at installColorSpace (/home/travis/build/AtomLinter/linter-stylelint/node_modules/stylelint/node_modules/colorguard/node_modules/pipetteur/node_modules/onecolor/one-color-all-debug.js:97:32)
      at Object.<anonymous> (/home/travis/build/AtomLinter/linter-stylelint/node_modules/stylelint/node_modules/colorguard/node_modules/pipetteur/node_modules/onecolor/one-color-all-debug.js:218:1)
      at Module._compile (/home/travis/atom/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
      at Object.defineProperty.value [as .js] (/home/travis/atom/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
      at Module.load (/home/travis/atom/usr/share/atom/resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (/home/travis/atom/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
      at Object.<anonymous> (/home/travis/build/AtomLinter/linter-stylelint/node_modules/stylelint/node_modules/colorguard/node_modules/pipetteur/pipetteur.js:2:13)
      at Module._compile (/home/travis/atom/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
      at Object.defineProperty.value [as .js] (/home/travis/atom/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
      at Module.load (/home/travis/atom/usr/share/atom/resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (/home/travis/atom/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
      at Object.<anonymous> (/home/travis/build/AtomLinter/linter-stylelint/node_modules/stylelint/node_modules/colorguard/lib/colorguard.js:5:17)
      at Module._compile (/home/travis/atom/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
      at Object.defineProperty.value [as .js] (/home/travis/atom/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
      at Module.load (/home/travis/atom/usr/share/atom/resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (/home/travis/atom/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
      at Object.<anonymous> (/home/travis/build/AtomLinter/linter-stylelint/node_modules/stylelint/node_modules/colorguard/index.js:1:97)
      at Module._compile (/home/travis/atom/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
      at Object.defineProperty.value [as .js] (/home/travis/atom/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
      at Module.load (/home/travis/atom/usr/share/atom/resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (/home/travis/atom/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
      at Object.<anonymous> (/home/travis/build/AtomLinter/linter-stylelint/node_modules/stylelint/dist/rules/no-indistinguishable-colors/index.js:43:19)
      at Module._compile (/home/travis/atom/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
      at Object.defineProperty.value [as .js] (/home/travis/atom/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
      at Module.load (/home/travis/atom/usr/share/atom/resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (/home/travis/atom/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
      at Object.<anonymous> (/home/travis/build/AtomLinter/linter-stylelint/node_modules/stylelint/dist/rules/index.js:295:34)
      at Module._compile (/home/travis/atom/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
      at Object.defineProperty.value [as .js] (/home/travis/atom/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
      at Module.load (/home/travis/atom/usr/share/atom/resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (/home/travis/atom/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
      at Object.<anonymous> (/home/travis/build/AtomLinter/linter-stylelint/node_modules/stylelint/dist/postcssPlugin.js:27:14)
      at Module._compile (/home/travis/atom/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
      at Object.defineProperty.value [as .js] (/home/travis/atom/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
      at Module.load (/home/travis/atom/usr/share/atom/resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (/home/travis/atom/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
      at Object.<anonymous> (/home/travis/build/AtomLinter/linter-stylelint/node_modules/stylelint/dist/index.js:3:22)
      at Module._compile (/home/travis/atom/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
      at Object.defineProperty.value [as .js] (/home/travis/atom/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
      at Module.load (/home/travis/atom/usr/share/atom/resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (/home/travis/atom/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
      at Object.<anonymous> (/home/travis/build/AtomLinter/linter-stylelint/lib/index.js:3:17)
      at Module._compile (/home/travis/atom/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
      at Object.defineProperty.value [as .js] (/home/travis/atom/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
      at Module.load (/home/travis/atom/usr/share/atom/resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (/home/travis/atom/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
      at [object Object].<anonymous> (/home/travis/build/AtomLinter/linter-stylelint/spec/linter-stylelint-spec.js:6:16)
      at Object.<anonymous> (/home/travis/build/AtomLinter/linter-stylelint/spec/linter-stylelint-spec.js:5:1)
      at Module._compile (/home/travis/atom/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
      at Object.defineProperty.value [as .js] (/home/travis/atom/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
      at Module.load (/home/travis/atom/usr/share/atom/resources/app.asar/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (/home/travis/atom/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
      at module.exports (/home/travis/atom/usr/share/atom/resources/app.asar/src/initialize-test-window.js:71:17)
      at setupWindow (file:///home/travis/atom/usr/share/atom/resources/app.asar/static/index.js:86:5)
      at window.onload (file:///home/travis/atom/usr/share/atom/resources/app.asar/static/index.js:41:9)
```

**Comment by davidtheclark** [comment]
Uuuuuugh. So if there's no way to have this work except to fix one-color, and one-color doesn't think it'll get fixed ---- are we just stuck? Is there no other way around this, @Arcanemagus?

**Comment by davidtheclark** [comment]
@jeddy3 This might mean we have to disable the rule until colorguard is compatible. What do you think? 

@Arcanemagus Do you know of any automated tool we could run our code through to catch the kind of code that breaks Atom before it makes it into a release?

**Comment by Arcanemagus** [comment]
It's possible this could be fixed in one of the intermediary dependencies (pipetteur or colorguard)?

And unfortunately not that I know of, @steelbrain have you head of anything that would check for `eval()` usage?

**Comment by ntwb** [comment]
The [file contains](https://github.com/One-com/one-color/blob/master/one-color-all-debug.js#L1) `/*jshint evil:true, onevar:false*/`, so if there was a tool that checked for the existence for `evil:true` in he dependancy tree...

**Comment by steelbrain** [comment]
[`this`](https://github.com/One-com/one-color/blob/8d09dfeee4e17cb2aff7752cf4d66bcb6a2658d5/one-color-all-debug.js#L97) is the eval you guys are looking for

**Comment by ntwb** [comment]
> This might mean we have to disable the rule until colorguard is compatible.

I think we should do this so that version an AtomLinter/linter-stylelint can be released with _as many other_ stylelint 4.5.x features as possible.

**Comment by davidtheclark** [comment]
Yeah, I agree. I will look into this tonight. Or @jeddy3 if you get to it first --- I think we should cut a 4.5 release without that rule.

**Comment by ntwb** [comment]
See also that AtomLinter/linter-stylelint has "pinned" stylelint 4.4.0, no 4.5.x features are available in Atom once a release is pushed (currently not yet released) https://github.com/AtomLinter/linter-stylelint/pull/117

**Comment by Arcanemagus** [comment]
It's been released, since otherwise new users are getting a broken install as `^4.5.0` can't run under Atom.

**Comment by davidtheclark** [comment]
So, does this have to be a breaking change? It seems crappy since the rule has had such a short and buggy life. But I guess people could be relying on it.

**Comment by Munter** [comment]
We've talked it over a bit amongst the one-color contributors. And we believe it's worth dropping the original goal of minimal file size to make the library work in this case and others that block eval. We'll give the rewrite a shot on monday, and if we succeed I'll release an updated dependency chain that should fix this breakage.

**Comment by davidtheclark** [comment]
The rule has been removed in v5, so Atom linter should be able to move forward.

**Comment by Arcanemagus** [comment]
Yep, just waiting on the configs to update at this point :+1:

See https://github.com/AtomLinter/linter-stylelint/pull/122#issuecomment-195242063 for more details.

**Comment by Munter** [comment]
One-color v3.0.0 now runs without eval. Pipetteur has been updated to 2.0.0 to use the updated version. This should solve the problem
